# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHaSM34zoduMYM0P0N-IQY4asEFXx7is
"""

# -*- coding: utf-8 -*-
import streamlit as st
import hashlib
import sqlite3
import math
import calendar
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# ==========================================================
# 1. 스트림릿 기본 설정 및 피그마 디자인 시스템 CSS 주입
# ==========================================================
st.set_page_config(
    page_title="캠퍼스 케어",
    page_icon="🖤",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# 피그마의 깔끔한 여백, 카드 라운딩, 컬러톤을 복제하기 위한 CSS
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap');
    html, body, [data-testid="stAppViewContainer"] {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: #F8F9FA;
    }

    /* 헤더 스타일 */
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px 0 20px 0;
    }
    .header-logo {
        font-size: 20px;
        font-weight: 700;
        color: #111111;
        display: flex;
        align-items: center;
        gap: 8px;
    }

    /* 피그마 둥근 카드 스타일 */
    .figma-card {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.02);
    }

    /* 2분할 상태 요약 영역 */
    .health-status-container {
        display: flex;
        gap: 16px;
        margin-bottom: 16px;
    }
    .status-item {
        flex: 1;
        border-radius: 16px;
        padding: 18px;
    }
    .status-period {
        background-color: #FFF0F2;
        border: 1px solid #FFD1D8;
    }
    .status-academic {
        background-color: #FFF9E6;
        border: 1px solid #FFE0B2;
    }
    .status-title {
        font-size: 13px;
        font-weight: 500;
        color: #666666;
        display: flex;
        align-items: center;
        gap: 6px;
        margin-bottom: 6px;
    }
    .status-value {
        font-size: 18px;
        font-weight: 700;
    }

    /* 미니 통계 요약 카드 */
    .mini-metric-grid {
        display: flex;
        gap: 16px;
        margin-bottom: 20px;
    }
    .mini-card {
        flex: 1;
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 18px;
    }
    .mini-title {
        font-size: 12px;
        color: #888888;
        margin-bottom: 4px;
    }
    .mini-val {
        font-size: 20px;
        font-weight: 700;
        color: #111111;
    }

    /* 피그마 다크 테마 버튼 */
    div.stButton > button {
        background-color: #0F1016 !important;
        color: #FFFFFF !important;
        border-radius: 12px !important;
        border: none !important;
        font-weight: 500 !important;
        padding: 12px 20px !important;
        width: 100%;
    }
    div.stButton > button:hover {
        background-color: #2F3036 !important;
    }

    /* 학사일정 타임라인 */
    .timeline-item {
        border-left: 3px solid #EAECEF;
        padding-left: 16px;
        margin-bottom: 14px;
        position: relative;
    }
    .timeline-title {
        font-size: 14px;
        font-weight: 500;
        color: #111111;
    }
    .timeline-date {
        font-size: 12px;
        color: #888888;
    }

    /* 달력 범례 */
    .legend-container {
        display: flex;
        gap: 12px;
        font-size: 12px;
        color: #666666;
        margin-top: 10px;
        margin-bottom: 15px;
    }
    .legend-item {
        display: flex;
        align-items: center;
        gap: 4px;
    }
    .legend-color {
        width: 12px;
        height: 12px;
        border-radius: 50%;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================================
# 2. 통합 데이터베이스 (`campus_care.db`) 및 로직 설정
# ==========================================================
DB_NAME = "campus_care.db"
MIN_DATA_REQUIRED = 5

# 학사 일정 원본 데이터베이스 (파이썬 기반 상수 데이터)
ACADEMIC_SCHEDULE = [
    {"date": "2026.03.02", "event": "대체공휴일"},
    {"date": "2026.03.03", "event": "입학식"},
    {"date": "2026.03.24", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.03.27", "event": "리더십 함양 캠프"},
    {"date": "2026.03.31", "event": "학교교육설명회(1학년)"},
    {"date": "2026.04.01", "event": "학교교육설명회(2학년)"},
    {"date": "2026.04.02", "event": "학교교육설명회(3학년)"},
    {"date": "2026.04.15", "event": "개교기념일"},
    {"date": "2026.04.24", "event": "1차지필(전학년)"},
    {"date": "2026.04.27", "event": "1차지필(전학년)"},
    {"date": "2026.04.28", "event": "1차지필(전학년)"},
    {"date": "2026.04.29", "event": "1차지필(전학년)"},
    {"date": "2026.05.01", "event": "노동절"},
    {"date": "2026.05.04", "event": "체육한마당"},
    {"date": "2026.05.05", "event": "어린이날"},
    {"date": "2026.05.07", "event": "학력평가(3학년)"},
    {"date": "2026.05.12", "event": "과목선택, 진로캠프(1학년)"},
    {"date": "2026.05.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.05.25", "event": "대체공휴일"},
    {"date": "2026.05.26", "event": "수학여행(2학년)"},
    {"date": "2026.05.27", "event": "수학여행(2학년)"},
    {"date": "2026.05.28", "event": "수학여행(2학년), 학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.05.29", "event": "수학여행(2학년)"},
    {"date": "2026.06.02", "event": "학부모수업공개"},
    {"date": "2026.06.03", "event": "지방선거"},
    {"date": "2026.06.12", "event": "진로체험(1학년)"},
    {"date": "2026.06.29", "event": "2차지필(전학년)"},
    {"date": "2026.06.30", "event": "2차지필(전학년)"},
    {"date": "2026.07.01", "event": "2차지필(전학년)"},
    {"date": "2026.07.02", "event": "2차지필(전학년)"},
    {"date": "2026.07.08", "event": "학력평가(3학년)"},
    {"date": "2026.07.17", "event": "제헌절"},
    {"date": "2026.07.22", "event": "방학식(여름방학 시작)"},
    {"date": "2026.08.13", "event": "개학"},
    {"date": "2026.08.17", "event": "대체공휴일"},
    {"date": "2026.08.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.09.02", "event": "학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.09.16", "event": "1차지필(3학년)"},
    {"date": "2026.09.17", "event": "1차지필(3학년)"},
    {"date": "2026.09.18", "event": "1차지필(3학년)"},
    {"date": "2026.09.24", "event": "추석연휴"},
    {"date": "2026.09.25", "event": "추석"},
    {"date": "2026.10.01", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.02", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.05", "event": "대체공휴일"},
    {"date": "2026.10.06", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.07", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.09", "event": "한글날"},
    {"date": "2026.10.20", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.10.27", "event": "진로탐방(1학년)"},
    {"date": "2026.10.28", "event": "진로탐방(1학년)"},
    {"date": "2026.10.29", "event": "진로탐방(1학년)"},
    {"date": "2026.11.02", "event": "학부모수업공개"},
    {"date": "2026.11.19", "event": "대학수학능력시험"},
    {"date": "2026.11.24", "event": "목요일 대체수업"},
    {"date": "2026.11.30", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.01", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.02", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.03", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.21", "event": "금요일 대체수업"},
    {"date": "2026.12.23", "event": "동아리발표회"},
    {"date": "2026.12.24", "event": "교내 축제"},
    {"date": "2026.12.25", "event": "성탄절"},
    {"date": "2026.12.28", "event": "방학식(겨울방학 시작)"},
    {"date": "2027.02.04", "event": "졸업식, 종업식"}
]
def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    # 1. 회원 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)
    # 2. 생리 기록 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS user_periods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    # 3. 카페인 및 수면 통합 정보 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sleep_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            date TEXT NOT NULL,
            remaining_caffeine REAL NOT NULL,
            is_luteal_phase INTEGER NOT NULL,
            prev_satisfaction REAL NOT NULL,
            actual_sleep REAL,
            sleep_satisfaction INTEGER,
            UNIQUE(username, date),
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    conn.commit()
    conn.close()

init_db()

def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# ==========================================================
# 3. 백엔드 알고리즘 이식
# ==========================================================
def register_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    try:
        cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_pw))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False
    finally:
        conn.close()

def login_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, hashed_pw))
    user = cursor.fetchone()
    conn.close()
    return True if user else False

# 사용자의 실제 생리 기록을 파싱하여 다음 생리 예정일 등을 예측 계산
def get_menstruation_predictions(username):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    if len(rows) < 1:
        return None

    startdates = [datetime.strptime(r[0], "%Y-%m-%d") for r in rows]
    avg_cycle = 28.0
    if len(startdates) >= 2:
        periods = []
        for i in range(1, len(startdates)):
            diff = (startdates[i] - startdates[i-1]).days
            if 21 <= diff <= 45:
                periods.append(diff)
        if periods:
            avg_cycle = sum(periods) / len(periods)

    next_start = startdates[-1] + timedelta(days=avg_cycle)
    return {
        "next_luteal_start": (next_start - timedelta(days=14)).strftime("%Y-%m-%d"),
        "next_luteal_end": next_start.strftime("%Y-%m-%d"),
        "next_period_start": next_start.strftime("%Y-%m-%d"),
        "avg_cycle": int(avg_cycle)
    }

# 데이터베이스 기록 및 주기 예측을 바탕으로 특정 날짜의 건강 상태 구분
def get_cycle_phase_for_date(username, target_date):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date, end_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    target_dt = target_date.replace(hour=0, minute=0, second=0, microsecond=0)

    # 1단계: 기록된 생리 기간과 겹치는지 체크
    for row in rows:
        st_dt = datetime.strptime(row[0], "%Y-%m-%d")
        et_dt = datetime.strptime(row[1], "%Y-%m-%d")
        if st_dt <= target_dt <= et_dt:
            return 2, "🩸 생리 기간", f"{row[0][5:].replace('-', '/')} ~ {row[1][5:].replace('-', '/')}"

    # 2단계: 예측된 다음 황체기와 겹치는지 체크
    pred = get_menstruation_predictions(username)
    if pred:
        luteal_start = datetime.strptime(pred["next_luteal_start"], "%Y-%m-%d")
        luteal_end = datetime.strptime(pred["next_luteal_end"], "%Y-%m-%d")
        if luteal_start <= target_dt < luteal_end:
            return 1, "🔥 황체기", f"{pred['next_luteal_start'][5:].replace('-', '/')} ~ {pred['next_luteal_end'][5:].replace('-', '/')}"

    return 0, "🌿 평상시", "안정기"

# 머신러닝 학습 모델 호출
def train_sleep_model(username):
    conn = sqlite3.connect(DB_NAME)
    df = pd.read_sql_query("SELECT * FROM sleep_records WHERE username = ?", conn, params=(username,))
    conn.close()

    complete_df = df.dropna(subset=["actual_sleep", "sleep_satisfaction"])
    if len(complete_df) < MIN_DATA_REQUIRED:
        return None

    X = complete_df[["remaining_caffeine", "is_luteal_phase", "prev_satisfaction"]]
    y = complete_df[["actual_sleep", "sleep_satisfaction"]]

    model = RandomForestRegressor(n_estimators=50, max_depth=4, random_state=42)
    model.fit(X, y)
    return model

# ==========================================================
# 4. 스트림릿 UI 레이아웃 및 파이썬 로직 전면 통합
# ==========================================================
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""

# --- A. 비로그인 상태 (회원가입/로그인 카드) ---
if not st.session_state["logged_in"]:
    st.markdown("<br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 4, 1])

    with col2:
        st.markdown("""
            <div style="text-align: center; margin-bottom: 24px;">
                <div style="background-color: #0F1016; width: 64px; height: 64px; border-radius: 18px; display: inline-flex; justify-content: center; align-items: center; margin-bottom: 16px;">
                    <span style="color: white; font-size: 28px;">♥</span>
                </div>
                <h2 style="font-weight: 700; margin: 0; color: #111;">캠퍼스 케어</h2>
                <p style="color: #666; font-size: 14px; margin-top: 4px;">나의 생리 주기 및 학업 일정 맞춤 솔루션</p>
            </div>
        """, unsafe_allow_html=True)

        menu = st.tabs(["로그인", "회원가입"])

        with menu[0]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            user = st.text_input("아이디", placeholder="아이디를 입력하세요", key="login_user")
            pw = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요", key="login_pw")

            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("로그인", key="btn_login"):
                if login_user(user, pw):
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = user
                    st.rerun()
                else:
                    st.error("❌ 아이디 또는 비밀번호가 일치하지 않습니다.")
            st.markdown("</div>", unsafe_allow_html=True)

        with menu[1]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            new_user = st.text_input("아이디", placeholder="새 아이디를 입력하세요", key="reg_user")
            new_pw = st.text_input("비밀번호", type="password", placeholder="새 비밀번호를 입력하세요", key="reg_pw")

            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("회원가입 완료", key="btn_register"):
                if new_user and new_pw:
                    if register_user(new_user, new_pw):
                        st.success("🎉 가입 성공! 로그인 탭에서 로그인해 주세요.")
                    else:
                        st.error("❌ 이미 존재하는 아이디입니다.")
                else:
                    st.warning("⚠️ 모든 칸을 입력해 주세요.")
            st.markdown("</div>", unsafe_allow_html=True)

# --- B. 로그인 완료 상태 (메인 대시보드 및 리포트) ---
else:
    username = st.session_state["username"]

    # 상단 정보 표시부
    col_h1, col_h2 = st.columns([4, 1])
    with col_h1:
        st.markdown(f"""
            <div class="header-logo">
                <span style="color: #0F1016; font-size: 22px;">♥</span> 캠퍼스 케어
            </div>
        """, unsafe_allow_html=True)
    with col_h2:
        if st.button("↳ 로그아웃", key="btn_logout"):
            st.session_state["logged_in"] = False
            st.session_state["username"] = ""
            st.rerun()

    now = datetime.now()
    st.markdown(f"""
        <div style="margin-top: 10px; margin-bottom: 16px;">
            <span style="color: #888; font-size: 13px;">{now.strftime('%Y년 %m월 %d일 %A')}</span>
            <h2 style="margin: 4px 0 0 0; font-weight: 700; color:#111;">{username}님 대시보드</h2>
        </div>
    """, unsafe_allow_html=True)

    # 하단 피그마 스타일 탭바 메뉴
    tab_home, tab_cal, tab_caff, tab_sleep = st.tabs(["㗊 홈", "📅 달력", "☕ 카페인", "🌙 수면"])

    # ----------------------------------------------------------
    # 🏠 홈 대시보드 탭
    # ----------------------------------------------------------
    with tab_home:
        # DB에서 실시간 사용자 주기와 일정을 동적으로 호출
        p_code, p_name, p_range = get_cycle_phase_for_date(username, now)

        # 오늘 날짜에 해당 학업 일정 확인
        today_str = now.strftime("%Y-%m-%d")
        today_event = "예정된 학사 일정이 없습니다."
        today_badge = "안정기"
        for sch in ACADEMIC_SCHEDULE:
            if sch["date"] == today_str:
                today_event = sch["event"]
                today_badge = "중요 마일스톤"
                break

        # DB에서 수면 피드백 요약 계산
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT AVG(sleep_satisfaction), remaining_caffeine FROM sleep_records WHERE username = ?", (username,))
        row = cursor.fetchone()
        avg_score = int(row[0]) if (row and row[0] is not None) else 0
        curr_caff = round(row[1], 1) if (row and row[1] is not None) else 0.0
        conn.close()

        # [UI 카드 1] 오늘의 건강 상태 및 학업 상태 (실시간 변수 매핑)
        st.markdown(f"""
            <div class="health-status-container">
                <div class="status-item status-period">
                    <div class="status-title">🩸 나의 신체 주기</div>
                    <div class="status-value" style="color: #FF4D6D;">{p_name}</div>
                    <div style="font-size: 12px; color: #888; margin-top: 4px;">범위: {p_range}</div>
                </div>
                <div class="status-item status-academic">
                    <div class="status-title">📅 오늘의 학사 일정</div>
                    <div class="status-value" style="color: #E28700;">{today_event}</div>
                    <div style="font-size: 12px; color: #D84B00; margin-top: 4px; font-weight: 500;">{today_badge}</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # [UI 카드 2] 이번 주 평균 수면 & 오늘 체내 카페인 요약 카드
        st.markdown(f"""
            <div class="mini-metric-grid">
                <div class="mini-card">
                    <div class="mini-title">🌙 나의 평균 수면 만족도</div>
                    <div class="mini-val">{avg_score if avg_score > 0 else '기록 없음'} <span style="font-size:14px; font-weight:normal; color:#888;">{ '점' if avg_score > 0 else ''}</span></div>
                </div>
                <div class="mini-card">
                    <div class="mini-title">☕ 오늘 남은 카페인</div>
                    <div class="mini-val">{curr_caff} <span style="font-size:14px; font-weight:normal; color:#888;">mg</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # [UI 카드 3] 생리 주기 예측 섹션
        pred = get_menstruation_predictions(username)
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 14px 0; font-size: 15px; font-weight: 700; color:#111;'>수집된 데이터 기반 주기 분석</h4>", unsafe_allow_html=True)

        if pred:
            st.markdown(f"""
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                    <div style="background: #F4F5F7; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">다음 생리 예정</span><br>
                        <strong style="font-size: 13px;">{pred['next_period_start']}</strong>
                    </div>
                    <div style="background: #F4F5F7; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">예상 황체기 시작</span><br>
                        <strong style="font-size: 13px;">{pred['next_luteal_start']}</strong>
                    </div>
                    <div style="background: #F4F5F7; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">평균 생리 주기</span><br>
                        <strong style="font-size: 13px;">{pred['avg_cycle']}일</strong>
                    </div>
                    <div style="background: #F4F5F7; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">현재 건강 상태</span><br>
                        <strong style="font-size: 13px;">{p_name}</strong>
                    </div>
                </div>
            """, unsafe_allow_html=True)
        else:
            st.info("💡 정확한 주기를 도출하기 위해 하단의 [달력] 탭에서 지난 생리 기록을 입력해 주세요.")
        st.markdown("</div>", unsafe_allow_html=True)

        # [UI 카드 4] 학사 일정 리스트
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 14px 0; font-size: 15px; font-weight: 700;'>다가오는 학업 마일스톤</h4>", unsafe_allow_html=True)
        for sch in ACADEMIC_SCHEDULE:
            sch_dt = datetime.strptime(sch["date"], "%Y-%m-%d")
            diff_days = (sch_dt - now.replace(hour=0, minute=0, second=0, microsecond=0)).days

            d_tag = f"D-{diff_days}" if diff_days > 0 else ("D-Day" if diff_days == 0 else f"D+{abs(diff_days)}")
            badge_color = "#EAECEF" if diff_days < 0 else ("#FF4D4D" if diff_days == 0 else "#0F1016")
            text_color = "white" if diff_days >= 0 else "#666"

            st.markdown(f"""
                <div class="timeline-item">
                    <div style="display: flex; justify-content: space-between; align-items: center;">
                        <div>
                            <div class="timeline-title">{sch['event']}</div>
                            <div class="timeline-date">{sch['date']}</div>
                        </div>
                        <span style="background-color: {badge_color}; color: {text_color}; font-size: 11px; font-weight:700; padding: 3px 8px; border-radius: 10px;">{d_tag}</span>
                    </div>
                </div>
            """, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 📅 달력 탭 (실시간 데이터 기반 달력 및 일정 매칭)
    # ----------------------------------------------------------
    with tab_cal:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 4px;">건강 & 캠퍼스 달력</h3>
            <p style="color: #888; font-size: 13px; margin-bottom: 16px;">파이썬 로직으로 계산된 생리 예정일과 학사 일정이 연동됩니다</p>
        """, unsafe_allow_html=True)

        # 현재 시간 기준 연도와 월 추출
        c_year = now.year
        c_month = now.month

        st.markdown(f"""
            <div class="figma-card" style="text-align: center;">
                <h4 style="margin-bottom: 15px; font-size: 16px;"><b>{c_year}년 {c_month}월</b></h4>
                <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 8px; font-weight: 500; font-size: 12px; color: #888; margin-bottom: 8px;">
                    <span style="color: #FF4D6D;">일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span style="color:#2E5BFF;">토</span>
                </div>
        """, unsafe_allow_html=True)

        # 달력 모듈을 이용하여 실제 해당하는 달의 첫 날 요일과 날짜 계산
        first_weekday, num_days = calendar.monthrange(c_year, c_month)
        # calendar weekday는 월요일이 0, 일요일이 6 이므로 일요일 시작 그리드로 보정
        start_empty_slots = (first_weekday + 1) % 7

        grid_html = '<div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 8px;">'

        # 빈칸 출력
        for _ in range(start_empty_slots):
            grid_html += '<span></span>'

        # 실제 일수 출력하며 상태 동적 판별
        for d in range(1, num_days + 1):
            check_date = datetime(c_year, c_month, d)
            p_code_d, _, _ = get_cycle_phase_for_date(username, check_date)

            bg_style = "background-color: transparent;"
            text_color = "#333"
            dot_html = ""

            # 주말 폰트 색상
            w_idx = (d + start_empty_slots - 1) % 7
            if w_idx == 0:
                text_color = "#FF4D6D"
            elif w_idx == 6:
                text_color = "#2E5BFF"

            # 학사일정 유무 체크 및 동적 검정 점 생성
            check_date_str = check_date.strftime("%Y-%m-%d")
            for sch in ACADEMIC_SCHEDULE:
                if sch["date"] == check_date_str:
                    dot_html = '<div style="width: 4px; height: 4px; background: #000; border-radius: 50%; margin: 2px auto 0 auto;"></div>'
                    break

            # 건강 주기 색상 매핑
            if p_code_d == 1:    # 황체기
                bg_style = "background-color: #FFF9E6; border-radius: 8px;"
            elif p_code_d == 2:  # 생리 기간
                bg_style = "background-color: #FFF0F2; border-radius: 8px;"

            # 오늘 날짜 강조 테두리
            if check_date.date() == now.date():
                bg_style = "background-color: #0F1016; color: white !important; border-radius: 8px;"
                dot_html = '<div style="width: 4px; height: 4px; background: #fff; border-radius: 50%; margin: 2px auto 0 auto;"></div>'
                text_color = "#fff"

            grid_html += f"""
                <div style="padding: 6px 0; font-size: 13px; font-weight: 500; {bg_style} color: {text_color}; text-align: center;">
                    {d}
                    {dot_html}
                </div>
            """

        grid_html += '</div>'
        st.markdown(grid_html, unsafe_allow_html=True)
        st.markdown("""
            <div class="legend-container" style="justify-content: center;">
                <div class="legend-item"><div class="legend-color" style="background: #F8F9FA; border: 1px solid #ddd;"></div>평상시</div>
                <div class="legend-item"><div class="legend-color" style="background: #FFF9E6;"></div>황체기</div>
                <div class="legend-item"><div class="legend-color" style="background: #FFF0F2;"></div>생리 기간</div>
                <div class="legend-item"><div class="legend-color" style="background: #000000;"></div>학사 일정</div>
            </div>
            </div>
        """, unsafe_allow_html=True)

        # 신규 주기 수동 등록 폼 (Figma 스타일)
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 14px 0; font-size: 15px;'><b>새 생리 기록 등록</b></h4>", unsafe_allow_html=True)
        with st.form("period_log_form"):
            start_date_input = st.date_input("생리 시작일", value=now.date())
            end_date_input = st.date_input("생리 종료일", value=now.date() + timedelta(days=5))
            submit_p = st.form_submit_button("✓ 생리 주기 데이터 등록")
            if submit_p:
                if end_date_input < start_date_input:
                    st.error("종료일이 시작일보다 빠를 수 없습니다.")
                else:
                    conn = sqlite3.connect(DB_NAME)
                    cursor = conn.cursor()
                    cursor.execute("""
                        INSERT INTO user_periods (username, start_date, end_date)
                        VALUES (?, ?, ?)
                    """, (username, start_date_input.strftime("%Y-%m-%d"), end_date_input.strftime("%Y-%m-%d")))
                    conn.commit()
                    conn.close()
                    st.success("새 주기가 기록되었습니다!")
                    st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # ☕ 카페인 탭 (실시간 물리적 하강 수식 그래프 구현)
    # ----------------------------------------------------------
    with tab_caff:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 4px;">실시간 카페인</h3>
            <p style="color: #888; font-size: 13px; margin-bottom: 16px;">마신 카페인의 시간 흐름에 따른 체내 잔여 성분을 동적 계산합니다</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT remaining_caffeine FROM sleep_records WHERE username = ? ORDER BY date DESC LIMIT 1", (username,))
        res = cursor.fetchone()
        caff_level = round(res[0], 1) if (res and res[0] is not None) else 0.0
        conn.close()

        status_tag = "안전" if caff_level < 10.0 else "주의"
        status_color = "#2ECC71" if caff_level < 10.0 else "#FF4D4D"

        st.markdown(f"""
            <div class="figma-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <span style="font-size: 14px; font-weight: 500; color: #666;">내 체내 잔류 카페인량</span>
                    <span style="background-color: {status_color}1a; color: {status_color}; font-size: 11px; font-weight: bold; padding: 2px 8px; border-radius: 12px;">{status_tag}</span>
                </div>
                <div style="font-size: 32px; font-weight: 700;">{caff_level} <span style="font-size: 16px; font-weight: normal; color: #888;">mg</span></div>
                <div style="margin-top: 10px; background-color: #F4F5F7; height: 6px; border-radius: 3px; position: relative;">
                    <div style="background-color: #0F1016; width: {min(100, int((caff_level/300)*100))}%; height: 100%; border-radius: 3px;"></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 실시간 카페인 추가 입력 부
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin:0 0 15px 0; font-size: 15px;'><b>카페인 섭취 입력</b></h4>", unsafe_allow_html=True)

        input_mg = st.number_input("섭취량 (mg)", min_value=0.0, value=120.0, step=10.0)
        input_time = st.time_input("섭취 시각", value=now.time())

        if st.button("☕ 카페인 기록 완료", key="btn_caff_add"):
            intake_dt = datetime.combine(now.date(), input_time)
            if intake_dt > now:
                intake_dt -= timedelta(days=1)

            hours_passed = (now - intake_dt).total_seconds() / 3600.0
            decay_val = input_mg * (0.5 ** (hours_passed / 5.0)) # 반감기 5시간 계산

            conn = sqlite3.connect(DB_NAME)
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction)
                VALUES (?, ?, ?, ?, 5.0)
            """, (username, now.strftime("%Y-%m-%d"), decay_val, 1 if p_code == 1 else 0))
            conn.commit()
            conn.close()
            st.success(f"카페인 {input_mg}mg 기록이 실시간 적용되었습니다.")
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 🌙 수면 리포트 및 실제 수면 피드백 탭 (차트 완전 연동)
    # ----------------------------------------------------------
    with tab_sleep:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 4px;">수면 분석</h3>
            <p style="color: #888; font-size: 13px; margin-bottom: 16px;">실제 기록된 어젯밤의 데이터로 매칭 그래프를 생성합니다</p>
        """, unsafe_allow_html=True)

        # SQLite 데이터베이스에서 사용자의 실제 수면 데이터 목록 가져오기
        conn = sqlite3.connect(DB_NAME)
        df_sleep = pd.read_sql_query("""
            SELECT date, actual_sleep, sleep_satisfaction
            FROM sleep_records
            WHERE username = ? AND actual_sleep IS NOT NULL
            ORDER BY date ASC LIMIT 7
        """, conn, params=(username,))
        conn.close()

        # 1. 실제 데이터 기반 차트 출력
        if not df_sleep.empty:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            st.markdown("<h4 style='margin: 0 0 15px 0; font-size: 15px;'><b>최근 수면 만족도 추이</b></h4>", unsafe_allow_html=True)

            # DB 데이터를 이용한 차트 구축
            dates = [datetime.strptime(d, "%Y-%m-%d").strftime("%m/%d") for d in df_sleep["date"]]
            scores = df_sleep["sleep_satisfaction"].tolist()

            fig, ax = plt.subplots(figsize=(10, 4.2))
            colors = ["#7EA192" if s >= 70 else ("#E9B569" if s >= 55 else "#D95C72") for s in scores]
            ax.bar(dates, scores, color=colors, width=0.45, zorder=3)

            ax.set_ylim(0, 100)
            ax.axhline(y=70, color="#7EA192", linestyle="--", linewidth=1, alpha=0.7, zorder=2)
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)
            ax.spines['left'].set_visible(False)
            ax.spines['bottom'].set_color('#EAECEF')
            ax.grid(axis='y', linestyle=':', color='#EAECEF', zorder=1)
            st.pyplot(fig)
            st.markdown("</div>", unsafe_allow_html=True)

            # 2. 실제 데이터 테이블형 리스트 출력
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            st.markdown("<h4 style='margin: 0 0 15px 0; font-size: 15px;'><b>상세 이력</b></h4>", unsafe_allow_html=True)
            for idx, row in df_sleep.iterrows():
                d_fmt = datetime.strptime(row['date'], "%Y-%m-%d").strftime("%m/%d")
                st.markdown(f"""
                    <div style="display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #F4F5F7;">
                        <div>
                            <strong style="font-size: 14px; color:#333;">{d_fmt}</strong>
                            <span style="font-size:12px; color:#888; margin-left: 8px;">실제 수면 {row['actual_sleep']}시간</span>
                        </div>
                        <span style="font-size:14px; font-weight:bold; color:#111;">만족도 {row['sleep_satisfaction']}점</span>
                    </div>
                """, unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        else:
            st.info("📊 데이터 분석을 위한 어젯밤 수면 기록이 아직 없습니다. 하단의 폼에 첫 만족도 피드백을 기록해 주세요!")

        # 3. 신규 수면 만족도 등록 폼
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 14px 0; font-size: 15px;'><b>어젯밤 수면 피드백 남기기</b></h4>", unsafe_allow_html=True)
        with st.form("sleep_feedback_form"):
            s_date = st.date_input("날짜", value=now.date() - timedelta(days=1))
            s_hours = st.slider("수면 시간 (시간 단위)", min_value=1.0, max_value=16.0, value=7.0, step=0.5)
            s_sat = st.slider("수면 만족도 점수 (100점 만점)", min_value=10, max_value=100, value=70, step=10)
            submit_s = st.form_submit_button("✓ 수면 데이터 등록하기")
            if submit_s:
                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction, actual_sleep, sleep_satisfaction)
                    VALUES (?, ?, 0.0, ?, 50.0, ?, ?)
                """, (username, s_date.strftime("%Y-%m-%d"), p_code, s_hours, s_sat))
                conn.commit()
                conn.close()
                st.success("데이터가 반영되었습니다!")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)
