# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHaSM34zoduMYM0P0N-IQY4asEFXx7is
"""

# -*- coding: utf-8 -*-
import streamlit as st
import hashlib
import sqlite3
import calendar
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# ==========================================================
# 1. 스트림릿 기본 설정 및 피그마 디자인 시스템 CSS 주입
# ==========================================================
st.set_page_config(
    page_title="캠퍼스 케어",
    page_icon="🖤",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# 피그마의 UI 요소(라운딩, 그림자, 내비게이션, 컴포넌트 여백)를 완벽하게 구현하기 위한 CSS
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap');

    html, body, [data-testid="stAppViewContainer"] {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: #F8F9FA;
    }

    /* 피그마 헤더 스타일 */
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 12px 0;
        margin-bottom: 20px;
    }
    .header-logo {
        font-size: 18px;
        font-weight: 700;
        color: #111111;
        display: flex;
        align-items: center;
        gap: 8px;
    }

    /* 카드 컴포넌트 */
    .figma-card {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.015);
    }

    /* 신체 주기 / 학사 일정 2단 카드 상단 배치 */
    .health-status-container {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .status-item {
        flex: 1;
        border-radius: 16px;
        padding: 16px;
    }
    .status-period {
        background-color: #FFF0F2;
        border: 1px solid #FFD1D8;
    }
    .status-academic {
        background-color: #FFF9E6;
        border: 1px solid #FFE0B2;
    }
    .status-title {
        font-size: 11px;
        font-weight: 500;
        color: #888888;
        display: flex;
        align-items: center;
        gap: 4px;
        margin-bottom: 6px;
    }
    .status-value {
        font-size: 15px;
        font-weight: 700;
        color: #FF4D6D;
    }
    .status-academic .status-value {
        color: #E28700;
    }

    /* 2열 수평 메트릭 카드 */
    .metric-row {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .metric-card {
        flex: 1;
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 16px;
        position: relative;
    }
    .metric-label {
        font-size: 11px;
        color: #888888;
        margin-bottom: 8px;
    }
    .metric-value {
        font-size: 22px;
        font-weight: 700;
        color: #111111;
    }

    /* 피그마 다크 테마 공통 버튼 스타일 */
    div.stButton > button {
        background-color: #0F1016 !important;
        color: #FFFFFF !important;
        border-radius: 12px !important;
        border: none !important;
        font-weight: 500 !important;
        padding: 10px 20px !important;
        font-size: 14px !important;
        width: 100%;
        transition: 0.2s ease;
    }
    div.stButton > button:hover {
        background-color: #2F3036 !important;
    }

    /* 타임라인 항목 */
    .timeline-item {
        border-left: 2px solid #EAECEF;
        padding-left: 14px;
        margin-bottom: 12px;
        position: relative;
    }
    .timeline-title {
        font-size: 13px;
        font-weight: 500;
        color: #111111;
    }
    .timeline-date {
        font-size: 11px;
        color: #888888;
        margin-top: 2px;
    }

    /* 카페인 선택 카드 */
    .caffeine-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 10px;
        margin-bottom: 16px;
    }
    .caffeine-item {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 12px;
        padding: 12px;
        text-align: center;
        cursor: pointer;
    }
    .caffeine-item:hover {
        border-color: #0F1016;
    }

    /* 수면 리포트 바차트 박스 */
    .chart-box {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 16px;
        margin-bottom: 16px;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================================
# 2. SQLite 데이터베이스 구성 및 초기화 (`campus_care.db`)
# ==========================================================
DB_NAME = "campus_care.db"
MIN_DATA_REQUIRED = 5

# 피그마 기획서에 명시된 고정 학사 일정 데이터
ACADEMIC_SCHEDULE = [
    {"date": "2026.03.02", "event": "대체공휴일"},
    {"date": "2026.03.03", "event": "입학식"},
    {"date": "2026.03.24", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.03.27", "event": "리더십 함양 캠프"},
    {"date": "2026.03.31", "event": "학교교육설명회(1학년)"},
    {"date": "2026.04.01", "event": "학교교육설명회(2학년)"},
    {"date": "2026.04.02", "event": "학교교육설명회(3학년)"},
    {"date": "2026.04.15", "event": "개교기념일"},
    {"date": "2026.04.24", "event": "1차지필(전학년)"},
    {"date": "2026.04.27", "event": "1차지필(전학년)"},
    {"date": "2026.04.28", "event": "1차지필(전학년)"},
    {"date": "2026.04.29", "event": "1차지필(전학년)"},
    {"date": "2026.05.01", "event": "노동절"},
    {"date": "2026.05.04", "event": "체육한마당"},
    {"date": "2026.05.05", "event": "어린이날"},
    {"date": "2026.05.07", "event": "학력평가(3학년)"},
    {"date": "2026.05.12", "event": "과목선택, 진로캠프(1학년)"},
    {"date": "2026.05.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.05.25", "event": "대체공휴일"},
    {"date": "2026.05.26", "event": "수학여행(2학년)"},
    {"date": "2026.05.27", "event": "수학여행(2학년)"},
    {"date": "2026.05.28", "event": "수학여행(2학년), 학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.05.29", "event": "수학여행(2학년)"},
    {"date": "2026.06.02", "event": "학부모수업공개"},
    {"date": "2026.06.03", "event": "지방선거"},
    {"date": "2026.06.12", "event": "진로체험(1학년)"},
    {"date": "2026.06.29", "event": "2차지필(전학년)"},
    {"date": "2026.06.30", "event": "2차지필(전학년)"},
    {"date": "2026.07.01", "event": "2차지필(전학년)"},
    {"date": "2026.07.02", "event": "2차지필(전학년)"},
    {"date": "2026.07.08", "event": "학력평가(3학년)"},
    {"date": "2026.07.17", "event": "제헌절"},
    {"date": "2026.07.22", "event": "방학식(여름방학 시작)"},
    {"date": "2026.08.13", "event": "개학"},
    {"date": "2026.08.17", "event": "대체공휴일"},
    {"date": "2026.08.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.09.02", "event": "학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.09.16", "event": "1차지필(3학년)"},
    {"date": "2026.09.17", "event": "1차지필(3학년)"},
    {"date": "2026.09.18", "event": "1차지필(3학년)"},
    {"date": "2026.09.24", "event": "추석연휴"},
    {"date": "2026.09.25", "event": "추석"},
    {"date": "2026.10.01", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.02", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.05", "event": "대체공휴일"},
    {"date": "2026.10.06", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.07", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.09", "event": "한글날"},
    {"date": "2026.10.20", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.10.27", "event": "진로탐방(1학년)"},
    {"date": "2026.10.28", "event": "진로탐방(1학년)"},
    {"date": "2026.10.29", "event": "진로탐방(1학년)"},
    {"date": "2026.11.02", "event": "학부모수업공개"},
    {"date": "2026.11.19", "event": "대학수학능력시험"},
    {"date": "2026.11.24", "event": "목요일 대체수업"},
    {"date": "2026.11.30", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.01", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.02", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.03", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.21", "event": "금요일 대체수업"},
    {"date": "2026.12.23", "event": "동아리발표회"},
    {"date": "2026.12.24", "event": "교내 축제"},
    {"date": "2026.12.25", "event": "성탄절"},
    {"date": "2026.12.28", "event": "방학식(겨울방학 시작)"},
    {"date": "2027.02.04", "event": "졸업식, 종업식"}
]

# 기준 오늘 날짜 (2026년 7월 15일 고정)
TODAY = datetime.strptime("2026-07-15", "%Y-%m-%d").date()

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    # 유저 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)
    # 생리 데이터 기록 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS user_periods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    # 카페인 및 수면 통합 분석 테이블 (기존 기록 에러를 방지하기 위해 컬럼 자동 정비)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sleep_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            date TEXT NOT NULL,
            remaining_caffeine REAL NOT NULL,
            is_luteal_phase INTEGER NOT NULL,
            prev_satisfaction REAL NOT NULL,
            actual_sleep REAL,
            sleep_satisfaction INTEGER,
            UNIQUE(username, date),
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    conn.commit()
    conn.close()

init_db()

# ==========================================================
# 3. 비즈니스 로직 및 알고리즘 구현
# ==========================================================
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def register_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    try:
        cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_pw))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False
    finally:
        conn.close()

def login_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, hashed_pw))
    user = cursor.fetchone()
    conn.close()
    return True if user else False

# 생리 주기 예측 로직 (SQLite 저장값 기반)
def get_menstruation_predictions(username):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    if len(rows) < 1:
        return None

    startdates = [datetime.strptime(r[0], "%Y-%m-%d") for r in rows]
    avg_cycle = 28.0

    # 기록이 2개 이상일 때 실주기 계산 반영
    if len(startdates) >= 2:
        periods = []
        for i in range(1, len(startdates)):
            diff = (startdates[i] - startdates[i-1]).days
            if 21 <= diff <= 45:
                periods.append(diff)
        if periods:
            avg_cycle = sum(periods) / len(periods)

    next_start = startdates[-1] + timedelta(days=avg_cycle)
    return {
        "next_luteal_start": (next_start - timedelta(days=14)).strftime("%Y-%m-%d"),
        "next_luteal_end": next_start.strftime("%Y-%m-%d"),
        "next_period_start": next_start.strftime("%Y-%m-%d"),
        "avg_cycle": int(avg_cycle)
    }

# 특정 날짜의 주기 구간 판별기
def get_cycle_phase_for_date(username, target_date):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date, end_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    target_dt = datetime.combine(target_date, datetime.min.time())

    # 1. 생리 기간 매칭 체크
    for row in rows:
        st_dt = datetime.strptime(row[0], "%Y-%m-%d")
        et_dt = datetime.strptime(row[1], "%Y-%m-%d")
        if st_dt <= target_dt <= et_dt:
            return 2, "🩸 생리 기간", f"예측: {row[0][5:].replace('-', '/')} ~ {row[1][5:].replace('-', '/')}"

    # 2. 황체기 기간 매칭 체크
    pred = get_menstruation_predictions(username)
    if pred:
        luteal_start = datetime.strptime(pred["next_luteal_start"], "%Y-%m-%d")
        luteal_end = datetime.strptime(pred["next_luteal_end"], "%Y-%m-%d")
        if luteal_start <= target_dt < luteal_end:
            return 1, "🔥 황체기", f"예측: {pred['next_luteal_start'][5:].replace('-', '/')} ~ {pred['next_luteal_end'][5:].replace('-', '/')}"

    return 0, "🌿 평상시", "안정기"

def get_upcoming_schedule():
    upcoming = []
    for item in ACADEMIC_SCHEDULE:
        clean_date_str = item["date"].replace(".", "-")
        event_date = datetime.strptime(clean_date_str, "%Y-%m-%d").date()

        # 오늘 날짜를 포함하여 다가오는 미래의 일정만 추출
        if event_date >= TODAY:
            d_day_num = (event_date - TODAY).days
            d_day_str = "D-Day" if d_day_num == 0 else f"D-{d_day_num}"

            upcoming.append({
                "date": item["date"],
                "event": item["event"],
                "d_day": d_day_str,
                "days_left": d_day_num
            })
    return sorted(upcoming, key=lambda x: x["days_left"])

# ==========================================================
# 4. 앱 로그인 분기점 관리
# ==========================================================
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""

if not st.session_state["logged_in"]:
    # --- 비로그인 로그인/회원가입 UI ---
    st.markdown("<br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        st.markdown("""
            <div style="text-align: center; margin-bottom: 24px;">
                <div style="background-color: #0F1016; width: 64px; height: 64px; border-radius: 20px; display: inline-flex; justify-content: center; align-items: center; margin-bottom: 16px;">
                    <span style="color: white; font-size: 28px;">♥</span>
                </div>
                <h2 style="font-weight: 700; margin: 0; color: #111;">캠퍼스 케어</h2>
                <p style="color: #666; font-size: 13px; margin-top: 4px;">건강한 캠퍼스 라이프를 위한 맞춤 케어</p>
            </div>
        """, unsafe_allow_html=True)

        menu = st.tabs(["로그인", "회원가입"])

        with menu[0]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            user = st.text_input("아이디", placeholder="아이디를 입력하세요", key="login_user")
            pw = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요", key="login_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("로그인", key="btn_login"):
                if user == "demo" and pw == "demo":
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = "demo"
                    st.rerun()
                elif login_user(user, pw):
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = user
                    st.rerun()
                else:
                    st.error("❌ 아이디 또는 비밀번호가 잘못되었습니다.")
            st.markdown("<p style='text-align:center; font-size:11px; color:#888; margin-top:15px;'>아무 아이디/비밀번호로 데모(demo/demo) 체험 가능합니다</p>", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        with menu[1]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            new_user = st.text_input("아이디", placeholder="새 아이디를 입력하세요", key="reg_user")
            new_pw = st.text_input("비밀번호", type="password", placeholder="새 비밀번호를 입력하세요", key="reg_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("회원가입 완료", key="btn_register"):
                if new_user and new_pw:
                    if register_user(new_user, new_pw):
                        st.success("🎉 가입 완료! 로그인해 주세요.")
                    else:
                        st.error("❌ 이미 존재하는 아이디입니다.")
                else:
                    st.warning("⚠️ 양식을 모두 채워주세요.")
            st.markdown("</div>", unsafe_allow_html=True)

else:
    # --- 로그인 이후 대시보드 진입 ---
    username = st.session_state["username"]

    # 상단 글로벌 바
    st.markdown(f"""
        <div class="header-container">
            <div class="header-logo">
                <span style="font-size: 20px;">🖤</span> 캠퍼스 케어
            </div>
            <div style="font-size: 12px; color: #888;">로그인 계정: <b>{username}</b></div>
        </div>
    """, unsafe_allow_html=True)

    if st.sidebar.button("로그아웃"):
        st.session_state["logged_in"] = False
        st.session_state["username"] = ""
        st.rerun()

    # 하단 탭 내비게이션 구축
    tab_home, tab_cal, tab_caff, tab_sleep = st.tabs(["㗊 홈", "📅 달력", "☕ 카페인", "🌙 수면 및 AI"])

    # ----------------------------------------------------------
    # 🏠 홈 대시보드 탭
    # ----------------------------------------------------------
    with tab_home:
        st.markdown(f"""
            <div style="margin-top: 5px; margin-bottom: 20px;">
                <span style="color: #888; font-size: 13px;">{TODAY.strftime('%Y년 %m월 %d일')}</span>
                <h2 style="margin: 4px 0 0 0; font-weight: 700; color:#111;">안녕하세요, {username}님 👋</h2>
            </div>
        """, unsafe_allow_html=True)

        # 오늘 날짜 정보 동적 가공
        p_code, p_name, p_range = get_cycle_phase_for_date(username, TODAY)

        # 오늘의 학사 일정 동적 매핑
        today_str = TODAY.strftime("%Y.%m.%d")
        today_event = "중요 일정이 없습니다."
        today_badge = "안정기"
        for sch in ACADEMIC_SCHEDULE:
            if sch["date"] == today_str:
                today_event = sch["event"]
                today_badge = "오늘 일정"
                break

        # 1. [오늘의 건강 상태 & 학사일정] 카드 렌더링
        st.markdown(f"""
            <div class="health-status-container">
                <div class="status-item status-period">
                    <div class="status-title">🩸 신체 주기 상태</div>
                    <div class="status-value">{p_name}</div>
                    <div style="font-size: 11px; color:#FF8597; margin-top: 4px;">{p_range}</div>
                </div>
                <div class="status-item status-academic">
                    <div class="status-title">📅 오늘 학사 일정</div>
                    <div class="status-value" style="color: #D48C00;">{today_event}</div>
                    <div style="font-size: 11px; color:#D48C00; margin-top: 4px;">{today_badge}</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 이번 주 평균 수면 & 체내 카페인 요약 카드
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT AVG(sleep_satisfaction), remaining_caffeine FROM sleep_records WHERE username = ?", (username,))
        row = cursor.fetchone()
        avg_score = int(row[0] * 20) if (row and row[0] is not None) else 0
        curr_caff = round(row[1], 1) if (row and row[1] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">이번 주 평균 수면</div>
                    <div class="metric-value">{avg_score if avg_score > 0 else '기록 없음'}<span style="font-size: 13px; font-weight: normal; color: #888;"> { '점 / 100' if avg_score > 0 else ''}</span></div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">오늘 체내 카페인</div>
                    <div class="metric-value">{curr_caff}<span style="font-size: 13px; font-weight: normal; color: #888;"> mg</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 2. [생리 주기 예측] 카드 렌더링
        pred = get_menstruation_predictions(username)
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 16px 0; font-size: 14px; font-weight: 700;'>생리 주기 예측</h4>", unsafe_allow_html=True)
        if pred:
            diff_p = (datetime.strptime(pred["next_period_start"], "%Y-%m-%d").date() - TODAY).days
            d_p_tag = "오늘 (D-0)" if diff_p == 0 else (f"D-{diff_p}" if diff_p > 0 else f"D+{abs(diff_p)}")

            st.markdown(f"""
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                    <div style="background: #F8F9FA; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">다음 생리 예정</span><br>
                        <strong style="font-size: 13px; color:#111;">{d_p_tag}</strong><br>
                        <span style="font-size: 11px; color:#888;">{pred['next_period_start']}</span>
                    </div>
                    <div style="background: #F8F9FA; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">다음 배란 예정</span><br>
                        <strong style="font-size: 13px; color:#111;">D+17</strong><br>
                        <span style="font-size: 11px; color:#888;">2026-08-01</span>
                    </div>
                    <div style="background: #F8F9FA; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">평균 주기</span><br>
                        <strong style="font-size: 13px; color:#111;">{pred['avg_cycle']}일</strong><br>
                        <span style="font-size: 11px; color:#888;">기록 데이터 기반</span>
                    </div>
                    <div style="background: #F8F9FA; padding: 12px; border-radius: 12px;">
                        <span style="font-size: 11px; color:#888;">현재 황체기</span><br>
                        <strong style="font-size: 13px; color:#111;">기록 없음</strong><br>
                        <span style="font-size: 11px; color:#888;">-</span>
                    </div>
                </div>
                <p style="font-size: 10px; color:#999; margin-top:12px; margin-bottom:0;">ⓘ 과거 기록 기반 예측입니다. 실제와 다를 수 있습니다.</p>
            """, unsafe_allow_html=True)
        else:
            st.info("💡 정확한 예측 데이터를 계산하기 위해 '달력' 탭에서 이전 생리 기록을 최소 1회 입력해 주세요.")
        st.markdown("</div>", unsafe_allow_html=True)

        # 3. [다가오는 학사 일정]
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 16px 0; font-size: 14px; font-weight: 700;'>다가오는 학사 일정</h4>", unsafe_allow_html=True)

        upcoming_events = get_upcoming_schedule()
        if upcoming_events:
            for sch in upcoming_events[:4]:  # 다가오는 일정 최대 4개
                st.markdown(f"""
                    <div class="timeline-item">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <div>
                                <div class="timeline-title">{sch['event']}</div>
                                <div class="timeline-date">{sch['date']}</div>
                            </div>
                            <span style="background-color: #F1F3F5; color: #495057; font-size: 11px; font-weight:600; padding: 4px 8px; border-radius: 20px;">{sch['d_day']}</span>
                        </div>
                    </div>
                """, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 📅 달력 탭 (코드 에러를 해결한 HTML 달력 및 일정 매칭)
    # ----------------------------------------------------------
    with tab_cal:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">캘린더</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">생리 주기와 학사 일정을 한눈에 확인하세요</p>
        """, unsafe_allow_html=True)

        c_year = TODAY.year
        c_month = TODAY.month

        # 피그마 달력 감싸는 화이트 카드 시작
        calendar_html = f"""
        <div class="figma-card" style="padding: 16px;">
            <div style="text-align: center; font-size: 16px; font-weight: 700; margin-bottom: 16px; color: #111;">
                {c_year}년 {c_month}월
            </div>
            <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px; font-weight: 500; font-size: 11px; color: #888; text-align: center; margin-bottom: 12px;">
                <span style="color: #FF4D6D;">일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span style="color:#2E5BFF;">토</span>
            </div>
        """

        first_weekday, num_days = calendar.monthrange(c_year, c_month)
        start_empty_slots = (first_weekday + 1) % 7

        calendar_html += '<div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px;">'

        for _ in range(start_empty_slots):
            calendar_html += '<span></span>'

        for d in range(1, num_days + 1):
            check_date = datetime(c_year, c_month, d).date()
            p_code_d, _, _ = get_cycle_phase_for_date(username, check_date)

            bg_style = "background-color: transparent;"
            text_color = "#333"
            dot_html = ""

            w_idx = (d + start_empty_slots - 1) % 7
            if w_idx == 0:
                text_color = "#FF4D6D"
            elif w_idx == 6:
                text_color = "#2E5BFF"

            check_date_str = check_date.strftime("%Y.%m.%d")
            for sch in ACADEMIC_SCHEDULE:
                if sch["date"] == check_date_str:
                    dot_html = '<div style="width: 4px; height: 4px; background: #000000; border-radius: 50%; margin: 2px auto 0 auto;"></div>'
                    break

            if p_code_d == 1:
                bg_style = "background-color: #FFF9E6; border-radius: 12px;"
            elif p_code_d == 2:
                bg_style = "background-color: #FFF0F2; border-radius: 12px;"

            if check_date == TODAY:
                bg_style = "background-color: #0F1016; color: #FFFFFF !important; border-radius: 12px;"
                text_color = "#FFFFFF"
                if dot_html:
                    dot_html = '<div style="width: 4px; height: 4px; background: #FFFFFF; border-radius: 50%; margin: 2px auto 0 auto;"></div>'

            calendar_html += f"""
                <div style="padding: 8px 0; font-size: 12px; font-weight: 500; {bg_style} color: {text_color}; text-align: center; position: relative;">
                    {d}
                    {dot_html}
                </div>
            """

        calendar_html += """
            </div>
            <div style="display: flex; gap: 10px; font-size: 11px; color: #888; justify-content: center; margin-top: 20px;">
                <span style="display:flex; align-items:center; gap:4px;"><span style="width:8px; height:8px; border-radius:50%; background:#F8F9FA; border:1px solid #ddd;"></span>평상시</span>
                <span style="display:flex; align-items:center; gap:4px;"><span style="width:8px; height:8px; border-radius:50%; background:#FFF9E6;"></span>황체기</span>
                <span style="display:flex; align-items:center; gap:4px;"><span style="width:8px; height:8px; border-radius:50%; background:#FFF0F2;"></span>생리 기간</span>
                <span style="display:flex; align-items:center; gap:4px;"><span style="width:4px; height:4px; border-radius:50%; background:#000;"></span>학사 일정</span>
            </div>
        </div>
        """

        st.markdown(calendar_html, unsafe_allow_html=True)

        st.markdown(f"""
            <div class="figma-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
                    <span style="font-size: 13px; font-weight: bold; color: #111;">{TODAY.strftime('%Y년 %m월 %d일')}</span>
                    <span style="background: #0F1016; color: white; font-size: 10px; padding: 2px 6px; border-radius: 4px;">오늘</span>
                </div>
                <div style="background-color: #FFF0F2; padding: 10px; border-radius: 8px; border-left: 3px solid #FF4D6D; font-size:12px; color: #FF4D6D; margin-bottom:12px;">
                    🩸 {p_name} ({p_range})
                </div>
                <div style="font-size: 13px; color: #333; font-weight: 500;">
                    🎓 <b>{today_event}</b><br>
                    <span style="font-size: 11px; color: #888;">{TODAY.strftime('%Y-%m-%d')} · 학사 일정</span>
                </div>
            </div>
        """, unsafe_allow_html=True)

        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color: #111;'>전체 학사 일정</h4>", unsafe_allow_html=True)
        for sch in ACADEMIC_SCHEDULE:
            sch_dt = datetime.strptime(sch["date"], "%Y.%m.%d").date()
            diff_days = (sch_dt - TODAY).days

            if diff_days > 0:
                day_badge = f"D-{diff_days}"
            elif diff_days == 0:
                day_badge = "오늘"
            else:
                day_badge = f"D+{abs(diff_days)}"

            st.markdown(f"""
                <div style="display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid #F8F9FA;">
                    <div>
                        <div style="font-size: 12px; font-weight: 500; color: #333;">{sch['event']}</div>
                        <div style="font-size: 10px; color: #888;">{sch['date']}</div>
                    </div>
                    <span style="background: #F1F3F5; color: #495057; font-size: 10px; font-weight: bold; padding: 2px 6px; border-radius: 8px;">{day_badge}</span>
                </div>
            """, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>새 생리 주기 등록</h4>", unsafe_allow_html=True)
        with st.form("period_log_form"):
            start_date_input = st.date_input("생리 시작일", value=TODAY)
            end_date_input = st.date_input("생리 종료일", value=TODAY + timedelta(days=5))
            submit_p = st.form_submit_button("✓ 생리 주기 데이터 저장")
            if submit_p:
                if end_date_input < start_date_input:
                    st.error("종료일이 시작일보다 빠를 수 없습니다.")
                else:
                    conn = sqlite3.connect(DB_NAME)
                    cursor = conn.cursor()
                    cursor.execute("""
                        INSERT INTO user_periods (username, start_date, end_date)
                        VALUES (?, ?, ?)
                    """, (username, start_date_input.strftime("%Y-%m-%d"), end_date_input.strftime("%Y-%m-%d")))
                    conn.commit()
                    conn.close()
                    st.success("데이터가 반영되었습니다!")
                    st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # ☕ 카페인 탭 (실시간 입력 및 현황 체크)
    # ----------------------------------------------------------
    with tab_caff:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">카페인 트래커</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">섭취한 카페인을 기록하고 적정 수면 시각을 안내받으세요</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT remaining_caffeine FROM sleep_records WHERE username = ? ORDER BY date DESC LIMIT 1", (username,))
        res = cursor.fetchone()
        caff_level = round(res[0], 1) if (res and res[0] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="figma-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <span style="font-size: 12px; color: #888;">체내 잔류 카페인</span>
                    <span style="background: #E8F8F0; color: #2ECC71; font-size: 10px; font-weight: bold; padding: 2px 6px; border-radius: 8px;">안전</span>
                </div>
                <div style="font-size: 28px; font-weight: 700; color: #111;">{caff_level} <span style="font-size: 14px; font-weight: normal; color: #888;">mg</span></div>
                <p style="font-size: 10px; color:#888; margin-top: 8px;">기준 300mg (일일 권장 최대치)</p>
            </div>
        """, unsafe_allow_html=True)

        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin:0 0 12px 0; font-size: 13px; font-weight: 700;'>카페인 기록 추가</h4>", unsafe_allow_html=True)

        st.markdown("""
            <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 16px;">
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">☕ 아메리카노<br><b style="color:#111;">128mg</b></div>
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">☕ 에스프레소<br><b style="color:#111;">64mg</b></div>
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">🍵 녹차 (350ml)<br><b style="color:#111;">25mg</b></div>
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">⚡ 에너지드링크<br><b style="color:#111;">80mg</b></div>
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">🥤 콜라 (355ml)<br><b style="color:#111;">34mg</b></div>
                <div style="background: #F8F9FA; padding: 10px; border-radius: 8px; text-align: center; font-size: 11px;">🫖 홍차 (240ml)<br><b style="color:#111;">47mg</b></div>
            </div>
        """, unsafe_allow_html=True)

        input_mg = st.number_input("카페인 양 (mg) 직접 입력", min_value=0.0, value=128.0, step=10.0)
        input_time = st.time_input("섭취 시각 선택", value=datetime.now().time())

        if st.button("➕ 카페인 추가"):
            intake_dt = datetime.combine(TODAY, input_time)
            # 기준일과 맞추기 위해 현재 시점에서 계산
            now_dt = datetime.combine(TODAY, datetime.now().time())
            hours_passed = max(0.0, (now_dt - intake_dt).total_seconds() / 3600.0)
            decay_val = input_mg * (0.5 ** (hours_passed / 5.0))

            conn = sqlite3.connect(DB_NAME)
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction)
                VALUES (?, ?, ?, ?, 5.0)
            """, (username, TODAY.strftime("%Y-%m-%d"), decay_val, 1 if p_code == 1 else 0))
            conn.commit()
            conn.close()
            st.success(f"카페인 {input_mg}mg 추가 및 섭취 경과 분석이 완료되었습니다.")
            st.rerun()

        st.markdown("""
            <div style="background-color:#F1F3F5; padding:12px; border-radius:12px; margin-top:16px; font-size:11px; color:#666;">
                💡 <b>카페인 반감기</b>는 약 5시간입니다. 오후 2시에 커피 한 잔을 마셨다면, 자정에도 절반 이상의 카페인이 체내에 남아 수면에 영향을 줄 수 있어요. 황체기에는 카페인 대사가 느려질 수 있으니 더욱 주의하세요.
            </div>
        """, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 🌙 수면 리포트 및 AI 분석 탭 (통계 차트 및 AI 활성화)
    # ----------------------------------------------------------
    with tab_sleep:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">수면 리포트 및 AI 분석</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">주간 수면 만족도를 확인하고 데이터 기반 AI 예측 컨디션을 확인하세요</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        df_sleep = pd.read_sql_query("""
            SELECT date, actual_sleep, sleep_satisfaction, remaining_caffeine
            FROM sleep_records
            WHERE username = ? AND actual_sleep IS NOT NULL
            ORDER BY date ASC LIMIT 7
        """, conn, params=(username,))
        conn.close()

        # 평균 및 위젯 산출
        avg_score = int(df_sleep["sleep_satisfaction"].mean() * 20) if not df_sleep.empty else 63
        avg_sleep = round(df_sleep["actual_sleep"].mean(), 1) if not df_sleep.empty else 6.3

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">이번 주 평균 만족 점수</div>
                    <div class="metric-value">{avg_score}<span style="font-size: 13px; font-weight: normal; color: #888;"> / 100</span></div>
                    <div style="font-size:11px; color:#E28700; margin-top:4px;">보통</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">평균 수면 시간</div>
                    <div class="metric-value">{avg_sleep}<span style="font-size: 13px; font-weight: normal; color: #888;"> 시간</span></div>
                    <div style="font-size:11px; color:#10B981; margin-top:4px;">적정 수면 상태</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 수면 기록 등록 폼
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>어젯밤 수면 시간 기록</h4>", unsafe_allow_html=True)
        with st.form("sleep_log_form"):
            sleep_date = st.date_input("수면 일자", value=TODAY - timedelta(days=1))
            actual_sleep = st.slider("수면 시간 (시간)", 0.0, 14.0, 7.0, 0.5)
            satisfaction = st.slider("수면 만족도 (1-5)", 1, 5, 4)
            submit_s = st.form_submit_button("✓ 수면 기록 저장")
            if submit_s:
                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction, actual_sleep, sleep_satisfaction)
                    VALUES (?, ?, 0.0, ?, 3.0, ?, ?)
                """, (username, sleep_date.strftime("%Y-%m-%d"), 1 if p_code == 1 else 0, actual_sleep, satisfaction))
                conn.commit()
                conn.close()
                st.success("수면 데이터가 기록되었습니다!")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

        # 주간 수면 추이 시각화 (matplotlib)
        if not df_sleep.empty:
            st.markdown("<div class='chart-box'>", unsafe_allow_html=True)
            st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>📊 지난 수면 추이</h4>", unsafe_allow_html=True)

            fig, ax1 = plt.subplots(figsize=(6, 3))
            ax2 = ax1.twinx()

            # 한글 깨짐 방지 폰트 적용
            plt.rcParams['font.family'] = 'NanumGothic' if 'NanumGothic' in [f.name for f in plt.font_manager.fontManager.ttflist] else 'sans-serif'

            ax1.bar(df_sleep["date"], df_sleep["actual_sleep"], color="#3B82F6", alpha=0.6, width=0.4, label="수면시간")
            ax2.plot(df_sleep["date"], df_sleep["sleep_satisfaction"], color="#EF4444", marker="o", linewidth=2, label="만족도")

            ax1.set_ylabel("시간 (h)", color="#3B82F6")
            ax2.set_ylabel("만족도 점수", color="#EF4444")
            fig.tight_layout()

            st.pyplot(fig)
            st.markdown("</div>", unsafe_allow_html=True)

        # AI 예측 섹션 (데이터 양 기반 분석)
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>🤖 머신러닝 AI 분석 엔진</h4>", unsafe_allow_html=True)

        if len(df_sleep) >= MIN_DATA_REQUIRED:
            X = df_sleep[["actual_sleep", "remaining_caffeine"]]
            y = df_sleep["sleep_satisfaction"]

            model = RandomForestRegressor(n_estimators=50, random_state=42)
            model.fit(X, y)

            st.info("⚙️ 분석 결과: 데이터 정밀 학습이 완료되었습니다.")
            st.markdown("<p style='font-size:12px; font-weight:700; margin-top:10px;'>💡 시뮬레이션: 내일 나의 컨디션 예측하기</p>", unsafe_allow_html=True)
            sim_sleep = st.slider("내일 목표 수면 시간", 3.0, 12.0, 7.5, 0.5)
            sim_caff = st.slider("내일 예상 카페인 섭취량 (mg)", 0, 600, 100, 50)

            pred = model.predict([[sim_sleep, sim_caff]])[0]
            pred_score = int(pred * 20)

            st.metric(label="예측 수면 점수", value=f"{pred_score}점 / 100점")
        else:
            st.warning(f"💡 분석 팁: 수면 만족도 데이터가 최소 {MIN_DATA_REQUIRED}일 이상 축적되어야 머신러닝 AI 예측 모델이 활성화됩니다. 현재 데이터 개수: {len(df_sleep)}개")
        st.markdown("</div>", unsafe_allow_html=True)