# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHaSM34zoduMYM0P0N-IQY4asEFXx7is
"""

# -*- coding: utf-8 -*-
import streamlit as st
import hashlib
import sqlite3
import calendar
import datetime
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
import numpy as np

# ==========================================================
# 1. 스트림릿 기본 설정 및 테마 수정 (#D1E0FC 전면 반영, 이모티콘 완전 삭제)
# ==========================================================
st.set_page_config(
    page_title="캠퍼스 케어",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# #D1E0FC 파스텔 블루 테마 적용 및 가독성 확보용 CSS
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap');

    html, body, [data-testid="stAppViewContainer"], [data-testid="stHeader"] {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: #F0F4FF !important; /* #D1E0FC 친화적인 전체 연한 배경 */
    }

    /* 전체 메인 앱 배경과 카드 디자인 테마화 */
    [data-testid="stMainBlockContainer"] {
        background-color: #F0F4FF !important;
    }

    /* 피그마 카드 디자인 */
    .figma-card {
        background: #FFFFFF !important;
        border: 2px solid #D1E0FC !important; /* 메인 컬러 테마 보더 적용 */
        border-radius: 16px !important;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0px 4px 12px rgba(209, 224, 252, 0.3);
    }

    /* 신체 주기 / 학사 일정 2단 카드 스타일 */
    .health-status-container {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .status-item {
        flex: 1;
        border-radius: 16px;
        padding: 16px;
    }
    .status-period {
        background-color: #FFEAEF;
        border: 1px solid #FFCCD5;
    }
    .status-academic {
        background-color: #EBF2FE;
        border: 1px solid #D1E0FC;
    }
    .status-title {
        font-size: 11px;
        font-weight: 500;
        color: #6B7280;
        margin-bottom: 6px;
    }
    .status-value {
        font-size: 15px;
        font-weight: 700;
        color: #FF4D6D;
    }
    .status-academic .status-value {
        color: #2563EB;
    }

    /* 2열 수평 메트릭 카드 */
    .metric-row {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .metric-card {
        flex: 1;
        background: #FFFFFF;
        border: 2px solid #D1E0FC;
        border-radius: 16px;
        padding: 16px;
    }
    .metric-label {
        font-size: 11px;
        color: #6B7280;
        margin-bottom: 8px;
    }
    .metric-value {
        font-size: 20px;
        font-weight: 700;
        color: #1E293B;
    }

    /* 전체 버튼 테마 일체화 (#D1E0FC 메인 칼라) */
    div.stButton > button {
        background-color: #D1E0FC !important;
        color: #1E293B !important;
        border-radius: 12px !important;
        border: 2px solid #B0C8F9 !important;
        font-weight: 700 !important;
        padding: 10px 20px !important;
        font-size: 14px !important;
        transition: all 0.2s ease-in-out;
        width: 100%;
    }
    div.stButton > button:hover {
        background-color: #B0C8F9 !important;
        border-color: #92B2F7 !important;
        transform: translateY(-1px);
    }

    /* 타임라인 레이아웃 */
    .timeline-item {
        border-left: 3px solid #D1E0FC;
        padding-left: 14px;
        margin-bottom: 12px;
    }
    .timeline-title {
        font-size: 13px;
        font-weight: 700;
        color: #1E293B;
    }
    .timeline-date {
        font-size: 11px;
        color: #6B7280;
        margin-top: 2px;
    }

    /* 탭 헤더 테마 색상 강제 지정 */
    button[data-baseweb="tab"] {
        color: #6B7280 !important;
    }
    button[data-baseweb="tab"][aria-selected="true"] {
        color: #2563EB !important;
        border-bottom-color: #2563EB !important;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================================
# 2. SQLite 데이터베이스 구성 및 초기화
# ==========================================================
DB_NAME = "campus_care.db"
MIN_DATA_REQUIRED = 3

ACADEMIC_SCHEDULE = [
    {"date": "2026.03.02", "event": "대체공휴일"},
    {"date": "2026.03.03", "event": "입학식"},
    {"date": "2026.03.24", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.03.27", "event": "리더십 함양 캠프"},
    {"date": "2026.03.31", "event": "학교교육설명회(1학년)"},
    {"date": "2026.04.01", "event": "학교교육설명회(2학년)"},
    {"date": "2026.04.02", "event": "학교교육설명회(3학년)"},
    {"date": "2026.04.15", "event": "개교기념일"},
    {"date": "2026.04.24", "event": "1차지필(전학년)"},
    {"date": "2026.04.27", "event": "1차지필(전학년)"},
    {"date": "2026.04.28", "event": "1차지필(전학년)"},
    {"date": "2026.04.29", "event": "1차지필(전학년)"},
    {"date": "2026.05.01", "event": "노동절"},
    {"date": "2026.05.04", "event": "체육한마당"},
    {"date": "2026.05.05", "event": "어린이날"},
    {"date": "2026.05.07", "event": "학력평가(3학년)"},
    {"date": "2026.05.12", "event": "과목선택, 진로캠프(1학년)"},
    {"date": "2026.05.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.05.25", "event": "대체공휴일"},
    {"date": "2026.05.26", "event": "수학여행(2학년)"},
    {"date": "2026.05.27", "event": "수학여행(2학년)"},
    {"date": "2026.05.28", "event": "수학여행(2학년), 학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.05.29", "event": "수학여행(2학년)"},
    {"date": "2026.06.02", "event": "학부모수업공개"},
    {"date": "2026.06.03", "event": "지방선거"},
    {"date": "2026.06.12", "event": "진로체험(1학년)"},
    {"date": "2026.06.29", "event": "2차지필(전학년)"},
    {"date": "2026.06.30", "event": "2차지필(전학년)"},
    {"date": "2026.07.01", "event": "2차지필(전학년)"},
    {"date": "2026.07.02", "event": "2차지필(전학년)"},
    {"date": "2026.07.08", "event": "학력평가(3학년)"},
    {"date": "2026.07.17", "event": "제헌절"},
    {"date": "2026.07.22", "event": "방학식(여름방학 시작)"},
    {"date": "2026.08.13", "event": "개학"},
    {"date": "2026.08.17", "event": "대체공휴일"},
    {"date": "2026.08.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.09.02", "event": "학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.09.16", "event": "1차지필(3학년)"},
    {"date": "2026.09.17", "event": "1차지필(3학년)"},
    {"date": "2026.09.18", "event": "1차지필(3학년)"},
    {"date": "2026.09.24", "event": "추석연휴"},
    {"date": "2026.09.25", "event": "추석"},
    {"date": "2026.10.01", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.02", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.05", "event": "대체공휴일"},
    {"date": "2026.10.06", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.07", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.09", "event": "한글날"},
    {"date": "2026.10.20", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.10.27", "event": "진로탐방(1학년)"},
    {"date": "2026.10.28", "event": "진로탐방(1학년)"},
    {"date": "2026.10.29", "event": "진로탐방(1학년)"},
    {"date": "2026.11.02", "event": "학부모수업공개"},
    {"date": "2026.11.19", "event": "대학수학능력시험"},
    {"date": "2026.11.24", "event": "목요일 대체수업"},
    {"date": "2026.11.30", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.01", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.02", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.03", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.21", "event": "금요일 대체수업"},
    {"date": "2026.12.23", "event": "동아리발표회"},
    {"date": "2026.12.24", "event": "교내 축제"},
    {"date": "2026.12.25", "event": "성탄절"},
    {"date": "2026.12.28", "event": "방학식(겨울방학 시작)"},
    {"date": "2027.02.04", "event": "졸업식, 종업식"}
]

# 3번 수정사항: 2026년 7월 15일 고정 제거 -> datetime 패키지를 이용한 자동 실제 현재 날짜 입력 변경
TODAY = datetime.date.today()

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS user_periods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sleep_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            date TEXT NOT NULL,
            remaining_caffeine REAL NOT NULL,
            is_luteal_phase INTEGER NOT NULL,
            prev_satisfaction REAL NOT NULL,
            sleep_start_time TEXT,
            sleep_end_time TEXT,
            actual_sleep REAL,
            sleep_satisfaction INTEGER,
            UNIQUE(username, date),
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    conn.commit()
    conn.close()

init_db()

# ==========================================================
# 3. 비즈니스 로직 및 핵심 함수 정의
# ==========================================================
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def register_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    try:
        cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_pw))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False
    finally:
        conn.close()

def login_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, hashed_pw))
    user = cursor.fetchone()
    conn.close()
    return True if user else False

def update_password(username, new_password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(new_password)
    cursor.execute("UPDATE users SET password = ? WHERE username = ?", (hashed_pw, username))
    conn.commit()
    conn.close()

def get_menstruation_predictions(username):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    if len(rows) < 1:
        return None

    startdates = []
    for r in rows:
        try:
            dt = datetime.datetime.strptime(r[0], "%Y-%m-%d").date()
            startdates.append(dt)
        except ValueError:
            continue

    if not startdates:
        return None

    avg_cycle = 28.0
    if len(startdates) >= 2:
        periods = []
        for i in range(1, len(startdates)):
            diff = (startdates[i] - startdates[i-1]).days
            if 21 <= diff <= 45:
                periods.append(diff)
        if periods:
            avg_cycle = sum(periods) / len(periods)

    next_start = startdates[-1] + datetime.timedelta(days=avg_cycle)
    return {
        "next_luteal_start": (next_start - datetime.timedelta(days=14)).strftime("%Y-%m-%d"),
        "next_luteal_end": next_start.strftime("%Y-%m-%d"),
        "next_period_start": next_start.strftime("%Y-%m-%d"),
        "avg_cycle": int(avg_cycle)
    }

def get_cycle_phase_for_date(username, target_date):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date, end_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    for row in rows:
        try:
            st_dt = datetime.datetime.strptime(row[0], "%Y-%m-%d").date()
            et_dt = datetime.datetime.strptime(row[1], "%Y-%m-%d").date()
            if st_dt <= target_date <= et_dt:
                return 2, "생리 기간", f"예측 주기: {row[0][5:].replace('-', '/')} ~ {row[1][5:].replace('-', '/')}"
        except ValueError:
            continue

    pred = get_menstruation_predictions(username)
    if pred:
        try:
            luteal_start = datetime.datetime.strptime(pred["next_luteal_start"], "%Y-%m-%d").date()
            luteal_end = datetime.datetime.strptime(pred["next_luteal_end"], "%Y-%m-%d").date()
            if luteal_start <= target_date < luteal_end:
                return 1, "황체기", f"예측 주기: {pred['next_luteal_start'][5:].replace('-', '/')} ~ {pred['next_luteal_end'][5:].replace('-', '/')}"
        except ValueError:
            pass

    return 0, "평상시", "신체 안정기"

# 1번 수정사항: 학사 일정을 오늘(당일)날짜부터 딱 한달(30일) 후까지만 수집하도록 필터링 변경
def get_upcoming_schedule_one_month():
    upcoming = []
    end_limit_date = TODAY + datetime.timedelta(days=30)
    for item in ACADEMIC_SCHEDULE:
        clean_date_str = item["date"].replace(".", "-")
        try:
            event_date = datetime.datetime.strptime(clean_date_str, "%Y-%m-%d").date()
        except ValueError:
            continue

        if TODAY <= event_date <= end_limit_date:
            d_day_num = (event_date - TODAY).days
            d_day_str = "D-Day" if d_day_num == 0 else f"D-{d_day_num}"
            upcoming.append({
                "date": item["date"],
                "event": item["event"],
                "d_day": d_day_str,
                "days_left": d_day_num
            })
    return sorted(upcoming, key=lambda x: x["days_left"])

# ==========================================================
# 4. 로그인 및 권한 관리 세션
# ==========================================================
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""

if not st.session_state["logged_in"]:
    st.markdown("<br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        st.markdown("""
            <div style="text-align: center; margin-bottom: 24px;">
                <h2 style="font-weight: 700; margin: 0; color: #1E293B;">캠퍼스 케어</h2>
                <p style="color: #64748B; font-size: 13px; margin-top: 4px;">건강한 대학 생활의 동반자</p>
            </div>
        """, unsafe_allow_html=True)

        menu = st.tabs(["로그인", "회원가입"])

        with menu[0]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            user = st.text_input("아이디", placeholder="아이디를 입력하세요", key="login_user")
            pw = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요", key="login_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("로그인", key="btn_login"):
                if user == "demo" and pw == "demo":
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = "demo"
                    st.rerun()
                elif login_user(user, pw):
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = user
                    st.rerun()
                else:
                    st.error("아이디 또는 비밀번호 정보가 정확하지 않습니다.")
            st.markdown("</div>", unsafe_allow_html=True)

        with menu[1]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            new_user = st.text_input("아이디", placeholder="가입할 아이디를 설정하세요", key="reg_user")
            new_pw = st.text_input("비밀번호", type="password", placeholder="가입할 비밀번호를 설정하세요", key="reg_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("회원등록 완료", key="btn_register"):
                if new_user and new_pw:
                    if register_user(new_user, new_pw):
                        st.success("회원가입이 정상 처리되었습니다. 로그인 탭에서 로그인 하세요.")
                    else:
                        st.error("이미 사용 중인 회원 정보 ID입니다.")
                else:
                    st.warning("아이디와 비밀번호를 빠짐없이 기입해 주세요.")
            st.markdown("</div>", unsafe_allow_html=True)

else:
    username = st.session_state["username"]

    st.markdown(f"""
        <div class="header-container">
            <div class="header-logo" style="color:#1E293B;">캠퍼스 케어</div>
            <div style="font-size: 12px; color: #475569;">계정명: <b>{username}</b></div>
        </div>
    """, unsafe_allow_html=True)

    # 6번 수정사항: 로그인 비밀번호 변경 기능 추가 (사이드바 메뉴 구현)
    with st.sidebar:
        st.markdown("### 계정 정보 관리")
        with st.expander("비밀번호 변경"):
            current_pw = st.text_input("현재 패스워드", type="password")
            new_pwd = st.text_input("새 패스워드", type="password")
            confirm_pwd = st.text_input("새 패스워드 확인", type="password")
            if st.button("비밀번호 변경 승인"):
                if username == "demo":
                    st.warning("데모 체험 계정은 비밀번호를 변경할 수 없습니다.")
                elif login_user(username, current_pw):
                    if new_pwd == confirm_pwd:
                        update_password(username, new_pwd)
                        st.success("비밀번호가 성공적으로 변경되었습니다.")
                    else:
                        st.error("새로 입력하신 비밀번호들이 서로 일치하지 않습니다.")
                else:
                    st.error("기존 비밀번호 검증이 실패하였습니다.")

        st.markdown("---")
        if st.button("시스템 로그아웃"):
            st.session_state["logged_in"] = False
            st.session_state["username"] = ""
            st.rerun()

    # 1번 수정사항: 달력 탭 이름을 '생리주기'로 명확하게 변경
    tab_home, tab_cal, tab_caff, tab_sleep = st.tabs(["홈", "생리주기", "카페인", "수면"])

    # ----------------------------------------------------------
    # 홈 탭
    # ----------------------------------------------------------
    with tab_home:
        st.markdown(f"""
            <div style="margin-top: 5px; margin-bottom: 20px;">
                <span style="color: #64748B; font-size: 13px;">{TODAY.strftime('%Y년 %m월 %d일')}</span>
                <h2 style="margin: 4px 0 0 0; font-weight: 700; color:#1E293B;">좋은 하루입니다, {username}님</h2>
            </div>
        """, unsafe_allow_html=True)

        p_code, p_name, p_range = get_cycle_phase_for_date(username, TODAY)

        # 오늘 당일 일정 매핑
        today_str = TODAY.strftime("%Y.%m.%d")
        today_event = "예정된 주요 일정이 없습니다."
        today_badge = "안정기"
        for sch in ACADEMIC_SCHEDULE:
            if sch["date"] == today_str:
                today_event = sch["event"]
                today_badge = "오늘 일정"
                break

        st.markdown(f"""
            <div class="health-status-container">
                <div class="status-item status-period">
                    <div class="status-title">생리 주기 위젯</div>
                    <div class="status-value">{p_name}</div>
                    <div style="font-size: 11px; color:#FF8597; margin-top: 4px;">{p_range}</div>
                </div>
                <div class="status-item status-academic">
                    <div class="status-title">오늘 학사일정 정보</div>
                    <div class="status-value">{today_event}</div>
                    <div style="font-size: 11px; color:#3B82F6; margin-top: 4px;">{today_badge}</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT AVG(sleep_satisfaction), remaining_caffeine FROM sleep_records WHERE username = ?", (username,))
        row = cursor.fetchone()
        avg_score = int(row[0] * 20) if (row and row[0] is not None) else 0
        curr_caff = round(row[1], 1) if (row and row[1] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">이번 주 평균 수면 만족 점수</div>
                    <div class="metric-value">{avg_score if avg_score > 0 else '미등록'}<span style="font-size: 13px; font-weight: normal; color: #64748B;"> { '점 / 100' if avg_score > 0 else ''}</span></div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">현재 혈중 카페인</div>
                    <div class="metric-value">{curr_caff}<span style="font-size: 13px; font-weight: normal; color: #64748B;"> mg</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 4번 수정사항: 홈화면 하단 불필요한 빈 요소를 삭제하고 직관적 한 달 이내 예정 학사 일정만 남김
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 16px 0; font-size: 14px; font-weight: 700; color:#1E293B;'>다가오는 대학 학사일정 (30일 이내)</h4>", unsafe_allow_html=True)

        one_month_events = get_upcoming_schedule_one_month()
        if one_month_events:
            for sch in one_month_events[:4]:
                st.markdown(f"""
                    <div class="timeline-item">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <div>
                                <div class="timeline-title">{sch['event']}</div>
                                <div class="timeline-date">{sch['date']}</div>
                            </div>
                            <span style="background-color: #EBF2FE; color: #2563EB; font-size: 11px; font-weight:600; padding: 4px 8px; border-radius: 20px;">{sch['d_day']}</span>
                        </div>
                    </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown("<p style='font-size: 12px; color: #64748B; margin:0;'>한 달 이내 등록된 일정이 존재하지 않습니다.</p>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 생리주기 탭 (1번 오류 해결 및 1, 4, 5번 수정 구현 완료)
    # ----------------------------------------------------------
    with tab_cal:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px; color:#1E293B;">생리주기 달력</h3>
            <p style="color: #64748B; font-size: 12px; margin-bottom: 16px;">개별 맞춤 생리 주기 기록과 30일 학사 연동 캘린더</p>
        """, unsafe_allow_html=True)

        c_year = TODAY.year
        c_month = TODAY.month

        # 에러 방지를 위해 pure 내장 함수로 안전하게 HTML 달력 그리기 구현
        calendar_html = f"""
        <div class="figma-card" style="padding: 16px;">
            <div style="text-align: center; font-size: 16px; font-weight: 700; margin-bottom: 16px; color: #1E293B;">
                {c_year}년 {c_month}월
            </div>
            <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px; font-weight: 500; font-size: 11px; color: #64748B; text-align: center; margin-bottom: 12px;">
                <span style="color: #FF4D6D;">일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span style="color:#2563EB;">토</span>
            </div>
        """

        first_weekday, num_days = calendar.monthrange(c_year, c_month)
        start_empty_slots = (first_weekday + 1) % 7

        calendar_html += '<div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px;">'

        for _ in range(start_empty_slots):
            calendar_html += '<span></span>'

        # 1번 핵심 수정: datetime.date 형식을 활용해 안전한 날짜 생성 루프 실행 (에러 완벽 예방)
        for d in range(1, num_days + 1):
            check_date = datetime.date(c_year, c_month, d)
            p_code_d, _, _ = get_cycle_phase_for_date(username, check_date)

            bg_style = "background-color: transparent;"
            text_color = "#1E293B"
            dot_html = ""

            w_idx = (d + start_empty_slots - 1) % 7
            if w_idx == 0:
                text_color = "#FF4D6D"
            elif w_idx == 6:
                text_color = "#2563EB"

            check_date_str = f"{c_year:04d}.{c_month:02d}.{d:02d}"
            for sch in ACADEMIC_SCHEDULE:
                if sch["date"] == check_date_str:
                    dot_html = '<div style="width: 5px; height: 5px; background: #2563EB; border-radius: 50%; margin: 2px auto 0 auto;"></div>'
                    break

            if p_code_d == 1:
                bg_style = "background-color: #FFF2CC; border-radius: 12px;"
            elif p_code_d == 2:
                bg_style = "background-color: #FFEAEF; border-radius: 12px;"

            if check_date == TODAY:
                bg_style = "background-color: #D1E0FC; color: #1E293B !important; border-radius: 12px; font-weight:bold;"

            calendar_html += f"""
                <div style="padding: 8px 0; font-size: 12px; font-weight: 500; {bg_style} color: {text_color}; text-align: center; position: relative;">
                    {d}
                    {dot_html}
                </div>
            """

        calendar_html += """
            </div>
        </div>
        """
        st.markdown(calendar_html, unsafe_allow_html=True)

        # 1번 & 5번 수정사항: 생리시작/종료를 각각 따로 입력받고 마우스/터치 클릭형 팝업 달력 선택 UI 연동
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color:#1E293B;'>새 생리일정 기록</h4>", unsafe_allow_html=True)

        # 5번: 직접 타이핑하지 않고 눌러서 달력을 팝업하는 컴포넌트 적용
        start_date_input = st.date_input("생리 시작한 날짜 선택", value=TODAY)
        end_date_input = st.date_input("생리 종료한 날짜 선택", value=TODAY + datetime.timedelta(days=5))

        if st.button("각각의 날짜 입력 완료"):
            if end_date_input < start_date_input:
                st.error("생리 종료 시점이 시작한 날짜보다 뒤에 위치해야 합니다.")
            else:
                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT INTO user_periods (username, start_date, end_date)
                    VALUES (?, ?, ?)
                """, (username, start_date_input.strftime("%Y-%m-%d"), end_date_input.strftime("%Y-%m-%d")))
                conn.commit()
                conn.close()
                st.success("해당 주기 이력이 정상 등록 처리되었습니다.")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

        # 1번 학사일정 표시 수정 (오늘 날짜 기준 1달 범위 한정 필터링)
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color: #1E293B;'>당일부터 한 달 이내 학사정보 목록</h4>", unsafe_allow_html=True)
        one_month_events = get_upcoming_schedule_one_month()
        if one_month_events:
            for sch in one_month_events:
                st.markdown(f"""
                    <div style="display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #E2E8F0;">
                        <div>
                            <div style="font-size: 12px; font-weight: 700; color: #1E293B;">{sch['event']}</div>
                            <div style="font-size: 10px; color: #64748B;">{sch['date']}</div>
                        </div>
                        <span style="background: #EBF2FE; color: #2563EB; font-size: 10px; font-weight: bold; padding: 4px 8px; border-radius: 8px;">{sch['d_day']}</span>
                    </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown("<p style='font-size: 12px; color: #64748B; margin:0;'>예정되어 있는 일정이 존재하지 않습니다.</p>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 카페인 탭 (8번 수정사항 완전 해결: 불필요한 음료 예시 완전 삭제)
    # ----------------------------------------------------------
    with tab_caff:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px; color:#1E293B;">카페인 트래커</h3>
            <p style="color: #64748B; font-size: 12px; margin-bottom: 16px;">개별 자유 설정을 통해 섭취한 시각과 수치를 기록 및 환산해 보세요</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT remaining_caffeine FROM sleep_records WHERE username = ? ORDER BY date DESC LIMIT 1", (username,))
        res = cursor.fetchone()
        caff_level = round(res[0], 1) if (res and res[0] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="figma-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <span style="font-size: 11px; color: #64748B;">실시간 잔류 카페인량</span>
                    <span style="background: #EBF2FE; color: #2563EB; font-size: 10px; font-weight: bold; padding: 2px 6px; border-radius: 8px;">체내 유지</span>
                </div>
                <div style="font-size: 26px; font-weight: 700; color: #1E293B;">{caff_level} <span style="font-size: 13px; font-weight: normal; color: #64748B;">mg</span></div>
            </div>
        """, unsafe_allow_html=True)

        # 8번 핵심 반영: 카페인 양 예시 전부 삭제 및 7번째 이미지 방식처럼 자유로운 시간/수치 선택 창 구현
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin:0 0 12px 0; font-size: 13px; font-weight: 700; color:#1E293B;'>카페인 정보 자유 조절 기입</h4>", unsafe_allow_html=True)

        input_mg = st.slider("카페인 섭취 용량 설정 (mg)", min_value=0, max_value=500, value=120, step=10)
        selected_time = st.time_input("정확한 음용 시간 선택", value=datetime.datetime.now().time())

        if st.button("카페인 정보 입력 완료"):
            intake_dt = datetime.datetime.combine(TODAY, selected_time)
            now_dt = datetime.datetime.combine(TODAY, datetime.datetime.now().time())
            hours_passed = max(0.0, (now_dt - intake_dt).total_seconds() / 3600.0)
            decay_val = input_mg * (0.5 ** (hours_passed / 5.0))

            conn = sqlite3.connect(DB_NAME)
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction)
                VALUES (?, ?, ?, ?, 3.0)
            """, (username, TODAY.strftime("%Y-%m-%d"), decay_val, 1 if p_code == 1 else 0))
            conn.commit()
            conn.close()
            st.success("작성하신 카페인 계측 수치가 반영되었습니다.")
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 수면 탭 (2번 수정사항 반영 및 4번 불필요한 요소 정리 완료)
    # ----------------------------------------------------------
    with tab_sleep:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px; color:#1E293B;">수면 분석 가이드</h3>
            <p style="color: #64748B; font-size: 12px; margin-bottom: 16px;">개인별 정확히 잠든 시간과 기상 시각을 데이터화하여 가장 완벽한 입면 타이밍을 추출합니다</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        df_sleep = pd.read_sql_query("""
            SELECT date, sleep_start_time, sleep_end_time, actual_sleep, sleep_satisfaction, remaining_caffeine
            FROM sleep_records
            WHERE username = ? AND actual_sleep IS NOT NULL
            ORDER BY date ASC LIMIT 7
        """, conn, params=(username,))
        conn.close()

        avg_score = int(df_sleep["sleep_satisfaction"].mean() * 20) if not df_sleep.empty else 60
        avg_sleep = round(df_sleep["actual_sleep"].mean(), 1) if not df_sleep.empty else 7.0

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">평균 만족 점수</div>
                    <div class="metric-value">{avg_score}<span style="font-size: 12px; font-weight: normal; color: #64748B;"> / 100</span></div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">평균 수면 지속시간</div>
                    <div class="metric-value">{avg_sleep}<span style="font-size: 12px; font-weight: normal; color: #64748B;"> 시간</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 2번 수정사항: 3번째 사진처럼 단순히 수면 시간이 아닌 몇 시에 자서 몇 시에 깼는지를 입력하도록 변경
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color:#1E293B;'>기상 및 취침 세부 시간 기록</h4>", unsafe_allow_html=True)

        with st.form("sleep_log_form_v3"):
            sleep_date = st.date_input("수면 발생 날짜 지정", value=TODAY - datetime.timedelta(days=1))
            col1, col2 = st.columns(2)
            with col1:
                bedtime_input = st.time_input("잠든 시각", value=datetime.time(23, 0))
            with col2:
                wake_time_input = st.time_input("기상 시각", value=datetime.time(7, 0))

            satisfaction = st.slider("주관적 숙면 만족 만족도 (1-5단계)", 1, 5, 4)
            submit_s = st.form_submit_button("취침 보고 등록하기")

            if submit_s:
                # 입면 기상시간 차이 연산으로 자동 실제 시간 계산
                dt_sleep = datetime.datetime.combine(sleep_date, bedtime_input)
                dt_wake = datetime.datetime.combine(sleep_date + datetime.timedelta(days=1), wake_time_input)
                if bedtime_input <= wake_time_input:
                    dt_wake = datetime.datetime.combine(sleep_date, wake_time_input)

                duration = round((dt_wake - dt_sleep).total_seconds() / 3600.0, 1)
                if duration < 0:
                    duration += 24.0

                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT OR REPLACE INTO sleep_records (
                        username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction,
                        sleep_start_time, sleep_end_time, actual_sleep, sleep_satisfaction
                    )
                    VALUES (?, ?, 0.0, ?, 3.0, ?, ?, ?, ?)
                """, (username, sleep_date.strftime("%Y-%m-%d"), 1 if p_code == 1 else 0,
                      bedtime_input.strftime("%H:%M"), wake_time_input.strftime("%H:%M"), duration, satisfaction))
                conn.commit()
                conn.close()
                st.success(f"취침 데이터 저장이 완료되었습니다 (계산 수면: {duration}시간)")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

        # 수면 만족도 시각화
        if not df_sleep.empty:
            st.markdown("<div class='chart-box' style='background:#FFFFFF; border: 2px solid #D1E0FC; border-radius: 16px; padding: 16px; margin-bottom: 16px;'>", unsafe_allow_html=True)
            st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color:#1E293B;'>지난 수면 지속성 차트</h4>", unsafe_allow_html=True)

            fig, ax1 = plt.subplots(figsize=(6, 2.8))
            ax1.bar(df_sleep["date"], df_sleep["actual_sleep"], color="#B0C8F9", alpha=0.8, width=0.4)
            ax2 = ax1.twinx()
            ax2.plot(df_sleep["date"], df_sleep["sleep_satisfaction"] * 20, color="#FF4D6D", marker="o", linewidth=2)

            ax1.set_ylabel("수면 시간", color="#1E293B")
            ax2.set_ylabel("만족도", color="#FF4D6D")
            fig.tight_layout()
            st.pyplot(fig)
            st.markdown("</div>", unsafe_allow_html=True)

        # 2번 수정사항: 모델도 수면시간 외 잠들고 깬 시각까지 입체 분석해 취침 추천 시각 연산
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color:#1E293B;'>AI 분석 기반 권장 취침 시각</h4>", unsafe_allow_html=True)

        if len(df_sleep) >= MIN_DATA_REQUIRED:
            X_data = []
            y_data = []
            for idx, row in df_sleep.iterrows():
                try:
                    time_obj = datetime.datetime.strptime(row["sleep_start_time"], "%H:%M").time()
                    minutes = time_obj.hour * 60 + time_obj.minute
                    X_data.append([minutes, row["remaining_caffeine"]])
                    y_data.append(row["sleep_satisfaction"])
                except Exception:
                    continue

            if len(X_data) >= MIN_DATA_REQUIRED:
                X = np.array(X_data)
                y = np.array(y_data)

                model = RandomForestRegressor(n_estimators=50, random_state=42)
                model.fit(X, y)

                all_times = np.array([[m, 0.0] for m in range(0, 1440, 30)])
                predictions = model.predict(all_times)
                best_idx = np.argmax(predictions)
                best_minutes = all_times[best_idx][0]

                best_hour = int(best_minutes // 60)
                best_minute = int(best_minutes % 60)

                st.info("개인 분석 모델에 따른 오늘 추천 취침 타이밍입니다.")
                st.markdown(f"""
                    <div style="background-color: #EBF2FE; border: 2px solid #D1E0FC; border-radius: 12px; padding: 14px; text-align: center;">
                        <div style="font-size: 11px; color: #475569; margin-bottom: 4px;">가장 수면 만족도가 높게 분석된 수면 개시 시각</div>
                        <strong style="font-size: 18px; color: #2563EB;">오후 {best_hour - 12 if best_hour >= 12 else best_hour}시 {best_minute:02d}분</strong>
                    </div>
                """, unsafe_allow_html=True)
            else:
                st.info("데이터가 더 축적되면 보다 정밀한 취침 개시 분석이 이루어집니다.")
        else:
            st.warning(f"적정 분석 데이터를 위해 수면 기록이 최소 {MIN_DATA_REQUIRED}일 이상 누적되어야 AI 분석 엔진이 작동합니다. 현재 데이터 개수: {len(df_sleep)}개")
        st.markdown("</div>", unsafe_allow_html=True)