# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHaSM34zoduMYM0P0N-IQY4asEFXx7is
"""

# -*- coding: utf-8 -*-
import streamlit as st
import hashlib
import sqlite3
import calendar
from datetime import datetime, timedelta, date, time
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
import numpy as np

# ==========================================================
# 1. 스트림릿 기본 설정 및 UI 테마 수정 (#D1E0FC 반영 및 이모티콘 제거)
# ==========================================================
st.set_page_config(
    page_title="캠퍼스 케어",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# UI 테마를 검정색에서 #D1E0FC로 변경 및 모든 이모티콘 제거
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap');

    html, body, [data-testid="stAppViewContainer"] {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: #F8F9FA;
    }

    /* 헤더 스타일 */
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 12px 0;
        margin-bottom: 20px;
    }
    .header-logo {
        font-size: 18px;
        font-weight: 700;
        color: #111111;
        display: flex;
        align-items: center;
        gap: 8px;
    }

    /* 카드 컴포넌트 */
    .figma-card {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.015);
    }

    /* 신체 주기 / 학사 일정 2단 카드 */
    .health-status-container {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .status-item {
        flex: 1;
        border-radius: 16px;
        padding: 16px;
    }
    .status-period {
        background-color: #FFF0F2;
        border: 1px solid #FFD1D8;
    }
    .status-academic {
        background-color: #EBF2FE;
        border: 1px solid #D1E0FC;
    }
    .status-title {
        font-size: 11px;
        font-weight: 500;
        color: #888888;
        display: flex;
        align-items: center;
        gap: 4px;
        margin-bottom: 6px;
    }
    .status-value {
        font-size: 15px;
        font-weight: 700;
        color: #FF4D6D;
    }
    .status-academic .status-value {
        color: #3B82F6;
    }

    /* 2열 수평 메트릭 카드 */
    .metric-row {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }
    .metric-card {
        flex: 1;
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 16px;
        position: relative;
    }
    .metric-label {
        font-size: 11px;
        color: #888888;
        margin-bottom: 8px;
    }
    .metric-value {
        font-size: 22px;
        font-weight: 700;
        color: #111111;
    }

    /* UI 테마 칼라 수정 (#D1E0FC 반영) */
    div.stButton > button {
        background-color: #D1E0FC !important;
        color: #1E293B !important;
        border-radius: 12px !important;
        border: 1px solid #B0C8F9 !important;
        font-weight: 700 !important;
        padding: 10px 20px !important;
        font-size: 14px !important;
        width: 100%;
        transition: 0.2s ease;
    }
    div.stButton > button:hover {
        background-color: #B0C8F9 !important;
    }

    /* 타임라인 항목 */
    .timeline-item {
        border-left: 2px solid #EAECEF;
        padding-left: 14px;
        margin-bottom: 12px;
        position: relative;
    }
    .timeline-title {
        font-size: 13px;
        font-weight: 500;
        color: #111111;
    }
    .timeline-date {
        font-size: 11px;
        color: #888888;
        margin-top: 2px;
    }

    /* 수면 리포트 바차트 박스 */
    .chart-box {
        background: #FFFFFF;
        border: 1px solid #EAECEF;
        border-radius: 16px;
        padding: 16px;
        margin-bottom: 16px;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================================
# 2. SQLite 데이터베이스 구성 및 초기화
# ==========================================================
DB_NAME = "campus_care.db"
MIN_DATA_REQUIRED = 3

ACADEMIC_SCHEDULE = [
    {"date": "2026.03.02", "event": "대체공휴일"},
    {"date": "2026.03.03", "event": "입학식"},
    {"date": "2026.03.24", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.03.27", "event": "리더십 함양 캠프"},
    {"date": "2026.03.31", "event": "학교교육설명회(1학년)"},
    {"date": "2026.04.01", "event": "학교교육설명회(2학년)"},
    {"date": "2026.04.02", "event": "학교교육설명회(3학년)"},
    {"date": "2026.04.15", "event": "개교기념일"},
    {"date": "2026.04.24", "event": "1차지필(전학년)"},
    {"date": "2026.04.27", "event": "1차지필(전학년)"},
    {"date": "2026.04.28", "event": "1차지필(전학년)"},
    {"date": "2026.04.29", "event": "1차지필(전학년)"},
    {"date": "2026.05.01", "event": "노동절"},
    {"date": "2026.05.04", "event": "체육한마당"},
    {"date": "2026.05.05", "event": "어린이날"},
    {"date": "2026.05.07", "event": "학력평가(3학년)"},
    {"date": "2026.05.12", "event": "과목선택, 진로캠프(1학년)"},
    {"date": "2026.05.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.05.25", "event": "대체공휴일"},
    {"date": "2026.05.26", "event": "수학여행(2학년)"},
    {"date": "2026.05.27", "event": "수학여행(2학년)"},
    {"date": "2026.05.28", "event": "수학여행(2학년), 학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.05.29", "event": "수학여행(2학년)"},
    {"date": "2026.06.02", "event": "학부모수업공개"},
    {"date": "2026.06.03", "event": "지방선거"},
    {"date": "2026.06.12", "event": "진로체험(1학년)"},
    {"date": "2026.06.29", "event": "2차지필(전학년)"},
    {"date": "2026.06.30", "event": "2차지필(전학년)"},
    {"date": "2026.07.01", "event": "2차지필(전학년)"},
    {"date": "2026.07.02", "event": "2차지필(전학년)"},
    {"date": "2026.07.08", "event": "학력평가(3학년)"},
    {"date": "2026.07.17", "event": "제헌절"},
    {"date": "2026.07.22", "event": "방학식(여름방학 시작)"},
    {"date": "2026.08.13", "event": "개학"},
    {"date": "2026.08.17", "event": "대체공휴일"},
    {"date": "2026.08.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.09.02", "event": "학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.09.16", "event": "1차지필(3학년)"},
    {"date": "2026.09.17", "event": "1차지필(3학년)"},
    {"date": "2026.09.18", "event": "1차지필(3학년)"},
    {"date": "2026.09.24", "event": "추석연휴"},
    {"date": "2026.09.25", "event": "추석"},
    {"date": "2026.10.01", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.02", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.05", "event": "대체공휴일"},
    {"date": "2026.10.06", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.07", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.09", "event": "한글날"},
    {"date": "2026.10.20", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.10.27", "event": "진로탐방(1학년)"},
    {"date": "2026.10.28", "event": "진로탐방(1학년)"},
    {"date": "2026.10.29", "event": "진로탐방(1학년)"},
    {"date": "2026.11.02", "event": "학부모수업공개"},
    {"date": "2026.11.19", "event": "대학수학능력시험"},
    {"date": "2026.11.24", "event": "목요일 대체수업"},
    {"date": "2026.11.30", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.01", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.02", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.03", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.21", "event": "금요일 대체수업"},
    {"date": "2026.12.23", "event": "동아리발표회"},
    {"date": "2026.12.24", "event": "교내 축제"},
    {"date": "2026.12.25", "event": "성탄절"},
    {"date": "2026.12.28", "event": "방학식(겨울방학 시작)"},
    {"date": "2027.02.04", "event": "졸업식, 종업식"}
]

# 3번 수정사항: 날짜를 2026-07-15 고정에서 datetime.now().date() 기반 실제 날짜로 수정
TODAY = datetime.now().date()

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS user_periods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sleep_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            date TEXT NOT NULL,
            remaining_caffeine REAL NOT NULL,
            is_luteal_phase INTEGER NOT NULL,
            prev_satisfaction REAL NOT NULL,
            sleep_start_time TEXT,
            sleep_end_time TEXT,
            actual_sleep REAL,
            sleep_satisfaction INTEGER,
            UNIQUE(username, date),
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    conn.commit()
    conn.close()

init_db()

# ==========================================================
# 3. 비즈니스 로직 및 헬퍼 함수
# ==========================================================
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def register_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    try:
        cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_pw))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False
    finally:
        conn.close()

def login_user(username, password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(password)
    cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, hashed_pw))
    user = cursor.fetchone()
    conn.close()
    return True if user else False

def update_password(username, new_password):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    hashed_pw = hash_password(new_password)
    cursor.execute("UPDATE users SET password = ? WHERE username = ?", (hashed_pw, username))
    conn.commit()
    conn.close()

def get_menstruation_predictions(username):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    if len(rows) < 1:
        return None

    startdates = [datetime.strptime(r[0], "%Y-%m-%d").date() for r in rows]
    avg_cycle = 28.0

    if len(startdates) >= 2:
        periods = []
        for i in range(1, len(startdates)):
            diff = (startdates[i] - startdates[i-1]).days
            if 21 <= diff <= 45:
                periods.append(diff)
        if periods:
            avg_cycle = sum(periods) / len(periods)

    next_start = startdates[-1] + timedelta(days=avg_cycle)
    return {
        "next_luteal_start": (next_start - timedelta(days=14)).strftime("%Y-%m-%d"),
        "next_luteal_end": next_start.strftime("%Y-%m-%d"),
        "next_period_start": next_start.strftime("%Y-%m-%d"),
        "avg_cycle": int(avg_cycle)
    }

def get_cycle_phase_for_date(username, target_date):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT start_date, end_date FROM user_periods WHERE username = ? ORDER BY start_date ASC", (username,))
    rows = cursor.fetchall()
    conn.close()

    for row in rows:
        st_dt = datetime.strptime(row[0], "%Y-%m-%d").date()
        et_dt = datetime.strptime(row[1], "%Y-%m-%d").date()
        if st_dt <= target_date <= et_dt:
            return 2, "생리 기간", f"예측: {row[0][5:].replace('-', '/')} ~ {row[1][5:].replace('-', '/')}"

    pred = get_menstruation_predictions(username)
    if pred:
        luteal_start = datetime.strptime(pred["next_luteal_start"], "%Y-%m-%d").date()
        luteal_end = datetime.strptime(pred["next_luteal_end"], "%Y-%m-%d").date()
        if luteal_start <= target_date < luteal_end:
            return 1, "황체기", f"예측: {pred['next_luteal_start'][5:].replace('-', '/')} ~ {pred['next_luteal_end'][5:].replace('-', '/')}"

    return 0, "평상시", "안정기"

# 당일날짜부터 한달 후까지 학사 일정을 수집하는 함수 (1번 수정사항)
def get_upcoming_schedule_one_month():
    upcoming = []
    end_limit_date = TODAY + timedelta(days=30)
    for item in ACADEMIC_SCHEDULE:
        clean_date_str = item["date"].replace(".", "-")
        try:
            event_date = datetime.strptime(clean_date_str, "%Y-%m-%d").date()
        except ValueError:
            continue

        if TODAY <= event_date <= end_limit_date:
            d_day_num = (event_date - TODAY).days
            d_day_str = "D-Day" if d_day_num == 0 else f"D-{d_day_num}"

            upcoming.append({
                "date": item["date"],
                "event": item["event"],
                "d_day": d_day_str,
                "days_left": d_day_num
            })
    return sorted(upcoming, key=lambda x: x["days_left"])

# ==========================================================
# 4. 세션 관리 및 로그인 분기
# ==========================================================
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""

if not st.session_state["logged_in"]:
    st.markdown("<br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        st.markdown("""
            <div style="text-align: center; margin-bottom: 24px;">
                <h2 style="font-weight: 700; margin: 0; color: #111;">캠퍼스 케어</h2>
                <p style="color: #666; font-size: 13px; margin-top: 4px;">건강한 대학 생활 도우미</p>
            </div>
        """, unsafe_allow_html=True)

        menu = st.tabs(["로그인", "회원가입"])

        with menu[0]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            user = st.text_input("아이디", placeholder="아이디를 입력하세요", key="login_user")
            pw = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요", key="login_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("로그인", key="btn_login"):
                if user == "demo" and pw == "demo":
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = "demo"
                    st.rerun()
                elif login_user(user, pw):
                    st.session_state["logged_in"] = True
                    st.session_state["username"] = user
                    st.rerun()
                else:
                    st.error("아이디 또는 비밀번호가 잘못되었습니다.")
            st.markdown("</div>", unsafe_allow_html=True)

        with menu[1]:
            st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
            new_user = st.text_input("아이디", placeholder="새 아이디를 입력하세요", key="reg_user")
            new_pw = st.text_input("비밀번호", type="password", placeholder="새 비밀번호를 입력하세요", key="reg_pw")
            st.markdown("<div style='margin-top: 15px;'></div>", unsafe_allow_html=True)
            if st.button("회원가입 완료", key="btn_register"):
                if new_user and new_pw:
                    if register_user(new_user, new_pw):
                        st.success("가입 완료! 로그인 탭에서 로그인 해주세요.")
                    else:
                        st.error("이미 존재하는 아이디입니다.")
                else:
                    st.warning("양식을 모두 작성해 주세요.")
            st.markdown("</div>", unsafe_allow_html=True)

else:
    username = st.session_state["username"]

    st.markdown(f"""
        <div class="header-container">
            <div class="header-logo">캠퍼스 케어</div>
            <div style="font-size: 12px; color: #888;">사용자: <b>{username}</b></div>
        </div>
    """, unsafe_allow_html=True)

    # 6번 수정사항: 로그인 비밀번호를 사이드바에서 안전하게 직접 변경 가능
    with st.sidebar:
        st.markdown("### 계정 설정")
        with st.expander("비밀번호 변경"):
            current_pw = st.text_input("현재 비밀번호", type="password")
            new_pwd = st.text_input("새로운 비밀번호", type="password")
            confirm_pwd = st.text_input("새 비밀번호 확인", type="password")
            if st.button("비밀번호 업데이트"):
                if username == "demo":
                    st.warning("데모 계정은 비밀번호를 변경할 수 없습니다.")
                elif login_user(username, current_pw):
                    if new_pwd == confirm_pwd:
                        update_password(username, new_pwd)
                        st.success("비밀번호가 변경되었습니다.")
                    else:
                        st.error("새 비밀번호가 서로 일치하지 않습니다.")
                else:
                    st.error("현재 비밀번호가 틀렸습니다.")

        st.markdown("---")
        if st.button("로그아웃"):
            st.session_state["logged_in"] = False
            st.session_state["username"] = ""
            st.rerun()

    # 1번 수정사항: 달력 탭이름을 '생리주기'로 변경
    tab_home, tab_cal, tab_caff, tab_sleep = st.tabs(["홈", "생리주기", "카페인", "수면"])

    # ----------------------------------------------------------
    # 홈 탭
    # ----------------------------------------------------------
    with tab_home:
        st.markdown(f"""
            <div style="margin-top: 5px; margin-bottom: 20px;">
                <span style="color: #888; font-size: 13px;">{TODAY.strftime('%Y년 %m월 %d일')}</span>
                <h2 style="margin: 4px 0 0 0; font-weight: 700; color:#111;">안녕하세요, {username}님</h2>
            </div>
        """, unsafe_allow_html=True)

        p_code, p_name, p_range = get_cycle_phase_for_date(username, TODAY)

        # 당일 학사 일정
        today_str = TODAY.strftime("%Y.%m.%d")
        today_event = "중요 일정이 없습니다."
        today_badge = "안정기"
        for sch in ACADEMIC_SCHEDULE:
            if sch["date"] == today_str:
                today_event = sch["event"]
                today_badge = "오늘 일정"
                break

        st.markdown(f"""
            <div class="health-status-container">
                <div class="status-item status-period">
                    <div class="status-title">신체 주기 상태</div>
                    <div class="status-value">{p_name}</div>
                    <div style="font-size: 11px; color:#FF8597; margin-top: 4px;">{p_range}</div>
                </div>
                <div class="status-item status-academic">
                    <div class="status-title">오늘 학사 일정</div>
                    <div class="status-value">{today_event}</div>
                    <div style="font-size: 11px; color:#3B82F6; margin-top: 4px;">{today_badge}</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT AVG(sleep_satisfaction), remaining_caffeine FROM sleep_records WHERE username = ?", (username,))
        row = cursor.fetchone()
        avg_score = int(row[0] * 20) if (row and row[0] is not None) else 0
        curr_caff = round(row[1], 1) if (row and row[1] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">이번 주 평균 수면 만족도</div>
                    <div class="metric-value">{avg_score if avg_score > 0 else '기록 없음'}<span style="font-size: 13px; font-weight: normal; color: #888;"> { '점 / 100' if avg_score > 0 else ''}</span></div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">오늘 체내 카페인</div>
                    <div class="metric-value">{curr_caff}<span style="font-size: 13px; font-weight: normal; color: #888;"> mg</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 4번 수정사항: 불필요한 메트릭/예측 카드 삭제 후 즉시 학사 일정 요약 표출
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 16px 0; font-size: 14px; font-weight: 700;'>한 달간 다가오는 학사 일정</h4>", unsafe_allow_html=True)

        one_month_events = get_upcoming_schedule_one_month()
        if one_month_events:
            for sch in one_month_events[:4]:
                st.markdown(f"""
                    <div class="timeline-item">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <div>
                                <div class="timeline-title">{sch['event']}</div>
                                <div class="timeline-date">{sch['date']}</div>
                            </div>
                            <span style="background-color: #EBF2FE; color: #3B82F6; font-size: 11px; font-weight:600; padding: 4px 8px; border-radius: 20px;">{sch['d_day']}</span>
                        </div>
                    </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown("<p style='font-size: 12px; color: #888;'>한 달 이내에 예정된 학사 일정이 없습니다.</p>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 생리주기 탭 (1번, 4번, 5번 완벽 해결)
    # ----------------------------------------------------------
    with tab_cal:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">생리주기 확인</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">캘린더 주기 정보와 실시간 학사 일정을 체크하세요</p>
        """, unsafe_allow_html=True)

        c_year = TODAY.year
        c_month = TODAY.month

        calendar_html = f"""
        <div class="figma-card" style="padding: 16px;">
            <div style="text-align: center; font-size: 16px; font-weight: 700; margin-bottom: 16px; color: #111;">
                {c_year}년 {c_month}월
            </div>
            <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px; font-weight: 500; font-size: 11px; color: #888; text-align: center; margin-bottom: 12px;">
                <span style="color: #FF4D6D;">일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span style="color:#2E5BFF;">토</span>
            </div>
        """

        first_weekday, num_days = calendar.monthrange(c_year, c_month)
        start_empty_slots = (first_weekday + 1) % 7

        calendar_html += '<div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 6px;">'

        for _ in range(start_empty_slots):
            calendar_html += '<span></span>'

        for d in range(1, num_days + 1):
            check_date = date(c_year, c_month, d)
            p_code_d, _, _ = get_cycle_phase_for_date(username, check_date)

            bg_style = "background-color: transparent;"
            text_color = "#333"
            dot_html = ""

            w_idx = (d + start_empty_slots - 1) % 7
            if w_idx == 0:
                text_color = "#FF4D6D"
            elif w_idx == 6:
                text_color = "#2E5BFF"

            check_date_str = check_date.strftime("%Y.%m.%d")
            for sch in ACADEMIC_SCHEDULE:
                if sch["date"] == check_date_str:
                    dot_html = '<div style="width: 4px; height: 4px; background: #3B82F6; border-radius: 50%; margin: 2px auto 0 auto;"></div>'
                    break

            if p_code_d == 1:
                bg_style = "background-color: #FFF9E6; border-radius: 12px;"
            elif p_code_d == 2:
                bg_style = "background-color: #FFF0F2; border-radius: 12px;"

            if check_date == TODAY:
                bg_style = "background-color: #D1E0FC; color: #1E293B !important; border-radius: 12px;"
                text_color = "#1E293B"

            calendar_html += f"""
                <div style="padding: 8px 0; font-size: 12px; font-weight: 500; {bg_style} color: {text_color}; text-align: center; position: relative;">
                    {d}
                    {dot_html}
                </div>
            """

        calendar_html += """
            </div>
        </div>
        """
        st.markdown(calendar_html, unsafe_allow_html=True)

        # 1, 4, 5번 수정사항: 생리 시작날짜와 종료날짜를 따로따로 분리 등록 및 직접 입력에서 누르는 팝업 캘린더 선택식으로 변경
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>생리 날짜 입력</h4>", unsafe_allow_html=True)

        # 날짜를 직접 타이핑하지 않고 눌러서 선택하는 캘린더 선택기
        start_date_input = st.date_input("생리 시작일 선택", value=TODAY)
        end_date_input = st.date_input("생리 종료일 선택", value=TODAY + timedelta(days=5))

        if st.button("주기 정보 따로 입력 완료"):
            if end_date_input < start_date_input:
                st.error("종료 예정일이 시작일보다 빠를 수 없습니다.")
            else:
                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT INTO user_periods (username, start_date, end_date)
                    VALUES (?, ?, ?)
                """, (username, start_date_input.strftime("%Y-%m-%d"), end_date_input.strftime("%Y-%m-%d")))
                conn.commit()
                conn.close()
                st.success("생리 기간 정보가 개별 저장되었습니다.")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

        # 1번 수정사항: 학사 일정을 당일날짜부터 한달 후까지 표시하도록 변경
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700; color: #111;'>당일부터 한 달 이내 학사 일정</h4>", unsafe_allow_html=True)
        one_month_events = get_upcoming_schedule_one_month()
        if one_month_events:
            for sch in one_month_events:
                st.markdown(f"""
                    <div style="display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid #F8F9FA;">
                        <div>
                            <div style="font-size: 12px; font-weight: 500; color: #333;">{sch['event']}</div>
                            <div style="font-size: 10px; color: #888;">{sch['date']}</div>
                        </div>
                        <span style="background: #EBF2FE; color: #3B82F6; font-size: 10px; font-weight: bold; padding: 2px 6px; border-radius: 8px;">{sch['d_day']}</span>
                    </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown("<p style='font-size: 12px; color: #888;'>당분간 예정된 학사 일정이 없습니다.</p>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 카페인 탭 (8번 완벽 반영: 카페인 양 예시 전부 삭제 및 시간 선택가능하게 변경)
    # ----------------------------------------------------------
    with tab_caff:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">카페인 측정</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">체내에 남은 카페인 양을 실시간으로 추적하세요</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute("SELECT remaining_caffeine FROM sleep_records WHERE username = ? ORDER BY date DESC LIMIT 1", (username,))
        res = cursor.fetchone()
        caff_level = round(res[0], 1) if (res and res[0] is not None) else 0.0
        conn.close()

        st.markdown(f"""
            <div class="figma-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <span style="font-size: 12px; color: #888;">실시간 잔류 카페인량</span>
                    <span style="background: #EBF2FE; color: #3B82F6; font-size: 10px; font-weight: bold; padding: 2px 6px; border-radius: 8px;">추적중</span>
                </div>
                <div style="font-size: 28px; font-weight: 700; color: #111;">{caff_level} <span style="font-size: 14px; font-weight: normal; color: #888;">mg</span></div>
            </div>
        """, unsafe_allow_html=True)

        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin:0 0 12px 0; font-size: 13px; font-weight: 700;'>카페인 정보 입력</h4>", unsafe_allow_html=True)

        # 8번 수정사항: 카페인 종류별 예시 그리드를 모두 제거하고 직접 자유 입력을 받음
        input_mg = st.number_input("카페인 수치 지정 (mg)", min_value=0.0, value=100.0, step=10.0)

        # 8번 수정사항: 7번째 사진의 슬라이더/셀렉터처럼 자유로운 시간 설정
        selected_time = st.time_input("섭취한 정확한 시각 선택", value=datetime.now().time())

        if st.button("카페인 섭취량 등록 완료"):
            intake_dt = datetime.combine(TODAY, selected_time)
            now_dt = datetime.combine(TODAY, datetime.now().time())
            hours_passed = max(0.0, (now_dt - intake_dt).total_seconds() / 3600.0)
            decay_val = input_mg * (0.5 ** (hours_passed / 5.0))

            conn = sqlite3.connect(DB_NAME)
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO sleep_records (username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction)
                VALUES (?, ?, ?, ?, 3.0)
            """, (username, TODAY.strftime("%Y-%m-%d"), decay_val, 1 if p_code == 1 else 0))
            conn.commit()
            conn.close()
            st.success("카페인 입력 데이터가 정상 저장되었습니다.")
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    # ----------------------------------------------------------
    # 수면 탭 (2번, 4번 완벽 해결: 몇시에 자서 일어났는지 입력 및 수면 예측 시스템 연동)
    # ----------------------------------------------------------
    with tab_sleep:
        st.markdown("""
            <h3 style="font-weight: 700; margin-bottom: 2px;">수면 예측 및 분석</h3>
            <p style="color: #888; font-size: 12px; margin-bottom: 16px;">개인별 정확한 취침 시간대 기록을 기반으로 한 최적 취침 가이드</p>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        df_sleep = pd.read_sql_query("""
            SELECT date, sleep_start_time, sleep_end_time, actual_sleep, sleep_satisfaction, remaining_caffeine
            FROM sleep_records
            WHERE username = ? AND actual_sleep IS NOT NULL
            ORDER BY date ASC LIMIT 7
        """, conn, params=(username,))
        conn.close()

        avg_score = int(df_sleep["sleep_satisfaction"].mean() * 20) if not df_sleep.empty else 60
        avg_sleep = round(df_sleep["actual_sleep"].mean(), 1) if not df_sleep.empty else 7.0

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">평균 만족 점수</div>
                    <div class="metric-value">{avg_score}<span style="font-size: 13px; font-weight: normal; color: #888;"> / 100</span></div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">평균 수면 시간</div>
                    <div class="metric-value">{avg_sleep}<span style="font-size: 13px; font-weight: normal; color: #888;"> 시간</span></div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        # 2번 수정사항: 3번째 사진처럼 몇시에 잠들고 깼는지 시간 단위로 정밀하게 입력
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>취침 및 기상 상세 시간 기록</h4>", unsafe_allow_html=True)

        with st.form("sleep_log_form_v2"):
            sleep_date = st.date_input("취침일 기준 날짜 선택", value=TODAY - timedelta(days=1))
            col1, col2 = st.columns(2)
            with col1:
                bedtime_input = st.time_input("잠든 시각", value=time(23, 0))
            with col2:
                wake_time_input = st.time_input("깬 시각", value=time(7, 0))

            satisfaction = st.slider("수면 만족 만족도 (1-5단계)", 1, 5, 4)
            submit_s = st.form_submit_button("상세 취침 정보 저장")

            if submit_s:
                dt_sleep = datetime.combine(sleep_date, bedtime_input)
                dt_wake = datetime.combine(sleep_date + timedelta(days=1), wake_time_input)
                if bedtime_input <= wake_time_input:
                    dt_wake = datetime.combine(sleep_date, wake_time_input)

                duration = round((dt_wake - dt_sleep).total_seconds() / 3600.0, 1)
                if duration < 0:
                    duration += 24.0

                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT OR REPLACE INTO sleep_records (
                        username, date, remaining_caffeine, is_luteal_phase, prev_satisfaction,
                        sleep_start_time, sleep_end_time, actual_sleep, sleep_satisfaction
                    )
                    VALUES (?, ?, 0.0, ?, 3.0, ?, ?, ?, ?)
                """, (username, sleep_date.strftime("%Y-%m-%d"), 1 if p_code == 1 else 0,
                      bedtime_input.strftime("%H:%M"), wake_time_input.strftime("%H:%M"), duration, satisfaction))
                conn.commit()
                conn.close()
                st.success(f"취침 분석 저장 완료: 총 {duration}시간 수면")
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

        if not df_sleep.empty:
            st.markdown("<div class='chart-box'>", unsafe_allow_html=True)
            st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>수면 만족 점수 및 시간 추이</h4>", unsafe_allow_html=True)

            fig, ax1 = plt.subplots(figsize=(6, 3))
            plt.rcParams['font.family'] = 'sans-serif'

            ax1.bar(df_sleep["date"], df_sleep["actual_sleep"], color="#B0C8F9", alpha=0.8, width=0.4, label="수면시간")
            ax2 = ax1.twinx()
            ax2.plot(df_sleep["date"], df_sleep["sleep_satisfaction"] * 20, color="#FF4D6D", marker="o", linewidth=2, label="만족도")

            ax1.set_ylabel("시간", color="#1E293B")
            ax2.set_ylabel("점수", color="#FF4D6D")
            fig.tight_layout()

            st.pyplot(fig)
            st.markdown("</div>", unsafe_allow_html=True)

        # 2번 수정사항: 잠들고 깬 시각 데이터까지 복합 분석하여 취침 시각 추천하는 모델 알고리즘 고도화
        st.markdown("<div class='figma-card'>", unsafe_allow_html=True)
        st.markdown("<h4 style='margin: 0 0 12px 0; font-size: 13px; font-weight: 700;'>개인화 취침 추천 모델 결과</h4>", unsafe_allow_html=True)

        if len(df_sleep) >= MIN_DATA_REQUIRED:
            X_data = []
            y_data = []
            for idx, row in df_sleep.iterrows():
                try:
                    time_obj = datetime.strptime(row["sleep_start_time"], "%H:%M").time()
                    minutes = time_obj.hour * 60 + time_obj.minute
                    X_data.append([minutes, row["remaining_caffeine"]])
                    y_data.append(row["sleep_satisfaction"])
                except Exception:
                    continue

            if len(X_data) >= MIN_DATA_REQUIRED:
                X = np.array(X_data)
                y = np.array(y_data)

                model = RandomForestRegressor(n_estimators=50, random_state=42)
                model.fit(X, y)

                all_times = np.array([[m, 0.0] for m in range(0, 1440, 30)])
                predictions = model.predict(all_times)
                best_idx = np.argmax(predictions)
                best_minutes = all_times[best_idx][0]

                best_hour = int(best_minutes // 60)
                best_minute = int(best_minutes % 60)

                st.info("과거 분석 이력 데이터를 활용한 적정 취침 시간입니다.")
                st.markdown(f"""
                    <div style="background-color: #EBF2FE; border: 1px solid #D1E0FC; border-radius: 12px; padding: 14px; text-align: center;">
                        <div style="font-size: 11px; color: #555; margin-bottom: 4px;">나에게 맞는 적정 추천 취침 시각</div>
                        <strong style="font-size: 18px; color: #1E293B;">오후 {best_hour - 12 if best_hour >= 12 else best_hour}시 {best_minute:02d}분</strong>
                    </div>
                """, unsafe_allow_html=True)
            else:
                st.info("정밀 추천 결과 분석을 위해 수면 데이터를 좀 더 추가해 주세요.")
        else:
            st.warning(f"적정 연산을 위해 {MIN_DATA_REQUIRED}개 이상의 수면 기록이 필요합니다. (현재 기록 개수: {len(df_sleep)}개)")
        st.markdown("</div>", unsafe_allow_html=True)