# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHaSM34zoduMYM0P0N-IQY4asEFXx7is
"""

# -*- coding: utf-8 -*-
import streamlit as st
import hashlib
import sqlite3
import calendar
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# ==========================================================
# 1. 스트림릿 기본 설정 및 피그마 디자인 시스템 CSS 주입
# ==========================================================
st.set_page_config(
    page_title="캠퍼스 케어",
    page_icon="🖤",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# 피그마의 UI 요소(라운딩, 그림자, 내비게이션, 컴포넌트 여백)를 완벽하게 구현하기 위한 CSS
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap');

    html, body, [data-testid="stAppViewContainer"] {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: #F8F9FA;
    }

    /* 피그마 헤더 스타일 */
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 16px 20px;
        background-color: #FFFFFF;
        border-bottom: 1px solid #EAEAEA;
    }

    .header-title {
        font-size: 18px;
        font-weight: 700;
        color: #111111;
    }

    /* 피그마 카드 컴포넌트 */
    .figma-card {
        background: #FFFFFF;
        border: 1px solid #EAEAEA;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.03);
    }

    .metric-row {
        display: flex;
        gap: 12px;
        margin-bottom: 16px;
    }

    .metric-card {
        flex: 1;
        background: #FFFFFF;
        border: 1px solid #EAEAEA;
        border-radius: 12px;
        padding: 16px;
        text-align: left;
    }

    .metric-label {
        font-size: 12px;
        color: #888888;
        margin-bottom: 4px;
    }

    .metric-value {
        font-size: 20px;
        font-weight: 700;
        color: #111111;
    }

    /* 하단 내비게이션 바 */
    .bottom-nav {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        height: 64px;
        background-color: #FFFFFF;
        border-top: 1px solid #EAEAEA;
        display: flex;
        justify-content: space-around;
        align-items: center;
        z-index: 999;
    }

    .nav-item {
        display: flex;
        flex-direction: column;
        align-items: center;
        font-size: 11px;
        color: #888888;
        text-decoration: none;
        cursor: pointer;
    }

    .nav-item.active {
        color: #111111;
        font-weight: 700;
    }

    .nav-icon {
        font-size: 20px;
        margin-bottom: 2px;
    }
    </style>
""", unsafe_allow_html=True)


# ==========================================================
# 2. 데이터베이스 초기화 및 사용자 정의 데이터 (학사 일정 등)
# ==========================================================
DB_NAME = "campus_care.db"

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    # 사용자 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            username TEXT PRIMARY KEY,
            password TEXT NOT NULL,
            name TEXT
        )
    """)
    # 수면 및 카페인 기록 테이블
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sleep_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT,
            date TEXT,
            sleep_start TEXT,
            sleep_end TEXT,
            actual_sleep REAL,
            caffeine_amount REAL,
            sleep_satisfaction INTEGER,
            FOREIGN KEY(username) REFERENCES users(username)
        )
    """)
    conn.commit()
    conn.close()

init_db()

# [사용자 요청 반영] 파이썬 코드로 구성된 실제 학사 일정 목록 데이터
ACADEMIC_SCHEDULE = [
    {"date": "2026.03.02", "event": "대체공휴일"},
    {"date": "2026.03.03", "event": "입학식"},
    {"date": "2026.03.24", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.03.27", "event": "리더십 함양 캠프"},
    {"date": "2026.03.31", "event": "학교교육설명회(1학년)"},
    {"date": "2026.04.01", "event": "학교교육설명회(2학년)"},
    {"date": "2026.04.02", "event": "학교교육설명회(3학년)"},
    {"date": "2026.04.15", "event": "개교기념일"},
    {"date": "2026.04.24", "event": "1차지필(전학년)"},
    {"date": "2026.04.27", "event": "1차지필(전학년)"},
    {"date": "2026.04.28", "event": "1차지필(전학년)"},
    {"date": "2026.04.29", "event": "1차지필(전학년)"},
    {"date": "2026.05.01", "event": "노동절"},
    {"date": "2026.05.04", "event": "체육한마당"},
    {"date": "2026.05.05", "event": "어린이날"},
    {"date": "2026.05.07", "event": "학력평가(3학년)"},
    {"date": "2026.05.12", "event": "과목선택, 진로캠프(1학년)"},
    {"date": "2026.05.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.05.25", "event": "대체공휴일"},
    {"date": "2026.05.26", "event": "수학여행(2학년)"},
    {"date": "2026.05.27", "event": "수학여행(2학년)"},
    {"date": "2026.05.28", "event": "수학여행(2학년), 학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.05.29", "event": "수학여행(2학년)"},
    {"date": "2026.06.02", "event": "학부모수업공개"},
    {"date": "2026.06.03", "event": "지방선거"},
    {"date": "2026.06.12", "event": "진로체험(1학년)"},
    {"date": "2026.06.29", "event": "2차지필(전학년)"},
    {"date": "2026.06.30", "event": "2차지필(전학년)"},
    {"date": "2026.07.01", "event": "2차지필(전학년)"},
    {"date": "2026.07.02", "event": "2차지필(전학년)"},
    {"date": "2026.07.08", "event": "학력평가(3학년)"},
    {"date": "2026.07.17", "event": "제헌절"},
    {"date": "2026.07.22", "event": "방학식(여름방학 시작)"},
    {"date": "2026.08.13", "event": "개학"},
    {"date": "2026.08.17", "event": "대체공휴일"},
    {"date": "2026.08.20", "event": "3학년 사설 모의고사"},
    {"date": "2026.09.02", "event": "학력평가(1,2학년), 평가원모의고사(3학년)"},
    {"date": "2026.09.16", "event": "1차지필(3학년)"},
    {"date": "2026.09.17", "event": "1차지필(3학년)"},
    {"date": "2026.09.18", "event": "1차지필(3학년)"},
    {"date": "2026.09.24", "event": "추석연휴"},
    {"date": "2026.09.25", "event": "추석"},
    {"date": "2026.10.01", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.02", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.05", "event": "대체공휴일"},
    {"date": "2026.10.06", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.07", "event": "1차지필(1,2학년)"},
    {"date": "2026.10.09", "event": "한글날"},
    {"date": "2026.10.20", "event": "학력평가(1,2,3학년)"},
    {"date": "2026.10.27", "event": "진로탐방(1학년)"},
    {"date": "2026.10.28", "event": "진로탐방(1학년)"},
    {"date": "2026.10.29", "event": "진로탐방(1학년)"},
    {"date": "2026.11.02", "event": "학부모수업공개"},
    {"date": "2026.11.19", "event": "대학수학능력시험"},
    {"date": "2026.11.24", "event": "목요일 대체수업"},
    {"date": "2026.11.30", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.01", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.02", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.03", "event": "2차지필(1,2학년)"},
    {"date": "2026.12.21", "event": "금요일 대체수업"},
    {"date": "2026.12.23", "event": "동아리발표회"},
    {"date": "2026.12.24", "event": "교내 축제"},
    {"date": "2026.12.25", "event": "성탄절"},
    {"date": "2026.12.28", "event": "방학식(겨울방학 시작)"},
    {"date": "2027.02.04", "event": "졸업식, 종업식"}
]

# 기준 오늘 날짜 (2026년 7월 15일 고정)
TODAY = datetime.strptime("2026-07-15", "%Y-%m-%d").date()


# ==========================================================
# 3. 데이터 가공 함수 및 헬퍼 함수
# ==========================================================
def make_hashes(password):
    return hashlib.sha256(str.encode(password)).hexdigest()

def check_hashes(password, hashed_text):
    if make_hashes(password) == hashed_text:
        return True
    return False

def get_upcoming_schedule():
    upcoming = []
    for item in ACADEMIC_SCHEDULE:
        # 점(.) 포맷을 대시(-) 포맷으로 파싱할 수 있게 전처리
        clean_date_str = item["date"].replace(".", "-")
        event_date = datetime.strptime(clean_date_str, "%Y-%m-%d").date()

        # 오늘 날짜를 포함하여 다가오는 미래의 일정만 추출
        if event_date >= TODAY:
            d_day_num = (event_date - TODAY).days
            d_day_str = "D-Day" if d_day_num == 0 else f"D-{d_day_num}"

            upcoming.append({
                "date": item["date"],
                "event": item["event"],
                "d_day": d_day_str,
                "days_left": d_day_num
            })
    return sorted(upcoming, key=lambda x: x["days_left"])


# ==========================================================
# 4. 세션 상태 및 라우팅 설정
# ==========================================================
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'username' not in st.session_state:
    st.session_state['username'] = ""
if 'page' not in st.session_state:
    st.session_state['page'] = "home"  # 기본 서브페이지는 홈


# ==========================================================
# 5. 로그인 및 회원가입 페이지 (인증 완료 전)
# ==========================================================
if not st.session_state['logged_in']:
    st.markdown("""
        <div style="text-align: center; margin-top: 40px; margin-bottom: 24px;">
            <span style="font-size: 40px;">🎓</span>
            <h2 style="font-size: 24px; font-weight: 700; margin-top: 12px; margin-bottom: 4px;">캠퍼스 케어</h2>
            <p style="color: #666; font-size: 14px;">대학 생활 건강 및 일정 파트너</p>
        </div>
    """, unsafe_allow_html=True)

    auth_tab1, auth_tab2 = st.tabs(["로그인", "회원가입"])

    with auth_tab1:
        with st.form("login_form"):
            login_id = st.text_input("아이디", placeholder="아이디를 입력하세요")
            login_pw = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요")
            login_btn = st.form_submit_button("로그인")

            if login_btn:
                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("SELECT password FROM users WHERE username = ?", (login_id,))
                user_data = cursor.fetchone()
                conn.close()

                # 데모 로그인 지원
                if login_id == "demo" and login_pw == "demo":
                    st.session_state['logged_in'] = True
                    st.session_state['username'] = "demo"
                    st.rerun()
                elif user_data and check_hashes(login_pw, user_data[0]):
                    st.session_state['logged_in'] = True
                    st.session_state['username'] = login_id
                    st.rerun()
                else:
                    st.error("아이디 또는 비밀번호가 틀렸습니다.")

    with auth_tab2:
        with st.form("signup_form"):
            new_id = st.text_input("아이디 설정", placeholder="사용할 아이디")
            new_name = st.text_input("이름 설정", placeholder="사용자 본명")
            new_pw = st.text_input("비밀번호 설정", type="password", placeholder="안전한 비밀번호")
            signup_btn = st.form_submit_button("가입하기")

            if signup_btn:
                if not new_id or not new_pw:
                    st.warning("아이디와 비밀번호를 모두 채워주세요.")
                else:
                    conn = sqlite3.connect(DB_NAME)
                    cursor = conn.cursor()
                    try:
                        cursor.execute("INSERT INTO users (username, password, name) VALUES (?, ?, ?)",
                                       (new_id, make_hashes(new_pw), new_name))
                        conn.commit()
                        st.success("회원가입 완료! 로그인 탭에서 로그인해 주세요.")
                    except sqlite3.IntegrityError:
                        st.error("이미 존재하는 아이디입니다.")
                    finally:
                        conn.close()

else:
    # ==========================================================
    # 6. 메인 서비스 영역 (로그인 완료 후)
    # ==========================================================
    username = st.session_state['username']

    # --- 6-1. 상단 내비게이션 바 역할의 탭 정의 ---
    menu_tab = st.radio(
        "메뉴 선택",
        ["🏠 홈", "☕ 수면/카페인", "🗓️ 학사 캘린더", "📊 수면 분석 및 AI"],
        horizontal=True,
        label_visibility="collapsed"
    )

    # ----------------------------------------------------------
    # 6-2. [탭 1] 🏠 홈 화면
    # ----------------------------------------------------------
    if menu_tab == "🏠 홈":
        st.markdown(f"""
            <div class="header-container" style="border-radius: 12px; margin-bottom: 20px;">
                <div class="header-title">🎓 캠퍼스 케어 홈</div>
                <div style="font-size: 13px; color: #555;">반갑습니다, <b>{username}</b>님</div>
            </div>
        """, unsafe_allow_html=True)

        # 오늘 일정 카드 요약
        st.markdown("""
            <div class="figma-card">
                <h3 style="margin-top: 0; font-size: 16px; font-weight: 700;">🕒 오늘 나의 하루 상태</h3>
                <p style="font-size: 13px; color: #555; margin-bottom: 0;">지난 밤 수면 상태를 기록하고 예측 건강 리포트를 받아보세요.</p>
            </div>
        """, unsafe_allow_html=True)

        # 다가오는 학사일정 D-Day 위젯 (새로운 학사 데이터 완벽 동기화)
        st.markdown("<h4 style='font-size: 15px; font-weight: 700; margin-bottom: 12px;'>🔔 다가오는 학사 일정</h4>", unsafe_allow_html=True)
        upcoming_events = get_upcoming_schedule()

        if upcoming_events:
            for event in upcoming_events[:4]:  # 최대 4개만 노출
                st.markdown(f"""
                <div style="
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    padding: 14px 18px;
                    border: 1px solid #E2E8F0;
                    border-radius: 12px;
                    background-color: #FFFFFF;
                    margin-bottom: 10px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.01);
                ">
                    <div>
                        <div style="font-size: 14.5px; font-weight: bold; color: #1E293B;">{event['event']}</div>
                        <div style="font-size: 12px; color: #64748B; margin-top: 2px;">{event['date']}</div>
                    </div>
                    <div style="
                        background-color: #EF4444;
                        padding: 4px 10px;
                        border-radius: 20px;
                        font-size: 12px;
                        font-weight: bold;
                        color: white;
                    ">
                        {event['d_day']}
                    </div>
                </div>
                """, unsafe_allow_html=True)
        else:
            st.info("남아있는 학사 일정이 없습니다.")

    # ----------------------------------------------------------
    # 6-3. [탭 2] ☕ 수면 및 카페인 기록기
    # ----------------------------------------------------------
    elif menu_tab == "☕ 수면/카페인":
        st.markdown("""
            <div class="figma-card">
                <h3 style="margin-top: 0; font-size: 16px; font-weight: 700;">☕ 오늘 카페인 & 지난 밤 수면 기록</h3>
                <p style="font-size: 13px; color: #666; margin-bottom: 16px;">매일 수면과 수면 전 카페인 섭취량을 축적하면 AI 정밀 분석이 가능해집니다.</p>
            </div>
        """, unsafe_allow_html=True)

        with st.form("health_record_form"):
            record_date = st.date_input("기록 일자", value=TODAY)

            col1, col2 = st.columns(2)
            with col1:
                sleep_start = st.time_input("수면 시작 시간", value=datetime.strptime("23:00", "%H:%M").time())
            with col2:
                sleep_end = st.time_input("기상 시간", value=datetime.strptime("07:00", "%H:%M").time())

            caffeine_amount = st.slider("☕ 카페인 섭취량 (mg)", 0, 800, 150, step=10,
                                        help="아메리카노 1잔은 약 150mg 입니다.")
            satisfaction = st.radio("😴 수면 만족도 (1 ~ 5)", [1, 2, 3, 4, 5], index=2, horizontal=True)

            submit_record = st.form_submit_button("기록 저장하기")

            if submit_record:
                # 시간 차 계산
                dt_start = datetime.combine(record_date, sleep_start)
                dt_end = datetime.combine(record_date, sleep_end)
                if dt_end < dt_start:
                    dt_end += timedelta(days=1)

                duration = round((dt_end - dt_start).seconds / 3600.0, 1)

                conn = sqlite3.connect(DB_NAME)
                cursor = conn.cursor()
                cursor.execute("""
                    INSERT INTO sleep_records (username, date, sleep_start, sleep_end, actual_sleep, caffeine_amount, sleep_satisfaction)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (username, record_date.strftime("%Y-%m-%d"), sleep_start.strftime("%H:%M"),
                      sleep_end.strftime("%H:%M"), duration, caffeine_amount, satisfaction))
                conn.commit()
                conn.close()
                st.success(f"성공적으로 기록되었습니다! (실제 계산된 총 수면시간: {duration}시간)")

    # ----------------------------------------------------------
    # 6-4. [탭 3] 🗓️ 학사 캘린더 리스트 (검색 지원)
    # ----------------------------------------------------------
    elif menu_tab == "🗓️ 학사 캘린더":
        st.markdown("""
            <div class="figma-card">
                <h3 style="margin-top: 0; font-size: 16px; font-weight: 700;">🗓️ 전체 학사 캘린더 조회</h3>
                <p style="font-size: 13px; color: #666; margin-bottom: 0;">2026학년도 ~ 2027학년도 일정을 날짜순으로 한눈에 파악하세요.</p>
            </div>
        """, unsafe_allow_html=True)

        search_query = st.text_input("🔍 일정 이름 또는 월(MM) 검색", placeholder="예: 지필, 축제, 05월")

        # 캘린더 데이터프레임 시각화
        df_cal = pd.DataFrame(ACADEMIC_SCHEDULE)
        df_cal.columns = ["날짜", "학사 일정 내용"]

        if search_query:
            # 월 형태로 간편 검색이 용이하게 가이드
            processed_query = search_query.replace("월", "")
            if len(processed_query) == 1 and processed_query.isdigit():
                processed_query = f".0{processed_query}."
            elif len(processed_query) == 2 and processed_query.isdigit():
                processed_query = f".{processed_query}."

            filtered_df = df_cal[
                df_cal["학사 일정 내용"].str.contains(search_query, case=False) |
                df_cal["날짜"].str.contains(processed_query)
            ]
            st.dataframe(filtered_df, use_container_width=True, hide_index=True)
        else:
            st.dataframe(df_cal, use_container_width=True, hide_index=True)

    # ----------------------------------------------------------
    # 6-5. [탭 4] 📊 수면 분석 및 AI 예측 리포트
    # ----------------------------------------------------------
    elif menu_tab == "📊 수면 분석 및 AI":
        st.markdown("""
            <div class="figma-card">
                <h3 style="margin-top: 0; font-size: 16px; font-weight: 700; margin-bottom: 2px;">수면 리포트</h3>
                <p style="color: #888; font-size: 12px; margin-bottom: 16px;">주간 수면 데이터를 확인하고 AI 예측을 위한 피드백을 남기세요</p>
            </div>
        """, unsafe_allow_html=True)

        conn = sqlite3.connect(DB_NAME)
        df_sleep = pd.read_sql_query("""
            SELECT date, actual_sleep, sleep_satisfaction, caffeine_amount
            FROM sleep_records
            WHERE username = ? AND actual_sleep IS NOT NULL
            ORDER BY date ASC LIMIT 7
        """, conn, params=(username,))
        conn.close()

        # 평균 및 위젯 산출
        avg_score = int(df_sleep["sleep_satisfaction"].mean() * 20) if not df_sleep.empty else 63
        avg_sleep = round(df_sleep["actual_sleep"].mean(), 1) if not df_sleep.empty else 6.3

        st.markdown(f"""
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">이번 주 평균 만족 점수</div>
                    <div class="metric-value">{avg_score}<span style="font-size: 13px; font-weight: normal; color: #888;"> / 100</span></div>
                    <div style="font-size:11px; color:#E28700; margin-top:4px;">보통</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">평균 수면 시간</div>
                    <div class="metric-value">{avg_sleep}<span style="font-size: 13px; font-weight: normal; color: #888;"> 시간</span></div>
                    <div style="font-size:11px; color:#10B981; margin-top:4px;">적정 수면 상태</div>
                </div>
            </div>
        """, unsafe_allow_html=True)

        st.markdown("#### 🤖 머신러닝 AI 분석 엔진")

        # 기계학습 구현 (데이터가 3개 이상 쌓여있을 때 활성화)
        if len(df_sleep) >= 3:
            X = df_sleep[["actual_sleep", "caffeine_amount"]]
            y = df_sleep["sleep_satisfaction"]

            model = RandomForestRegressor(n_estimators=50, random_state=42)
            model.fit(X, y)

            st.info("⚙️ 분석 결과: 데이터 정밀 학습이 완료되었습니다.")

            st.markdown("<p style='font-size:14px; font-weight:700;'>💡 시뮬레이션: 내일 나의 컨디션 예측하기</p>", unsafe_allow_html=True)
            sim_sleep = st.slider("내일 목표 수면 시간", 3.0, 10.0, 7.5, 0.5)
            sim_caff = st.slider("내일 예상 카페인 섭취량 (mg)", 0, 600, 100, 50)

            pred = model.predict([[sim_sleep, sim_caff]])[0]
            pred_score = int(pred * 20)

            st.metric(label="예측 수면 점수", value=f"{pred_score}점 / 100점")
        else:
            st.warning("💡 분석 팁: 수면 만족도 데이터가 최소 3일 이상 축적되어야 머신러닝 AI 예측 모델이 활성화됩니다. '수면/카페인' 메뉴에서 기록을 추가해 보세요!")

    # --- 로그아웃 영역 ---
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    if st.button("🔓 로그아웃"):
        st.session_state['logged_in'] = False
        st.session_state['username'] = ""
        st.rerun()